### ISSUE TITLE
Install odbc on linux get error

### ISSUE THREAD

**Issue by brunolucian** [rstats-db/odbc#102]
> install.packages("odbc")
Installing package into ‘/home/bruno/R/x86_64-pc-linux-gnu-library/3.2’
(as ‘lib’ is unspecified)
trying URL 'http://cran.rstudio.com/src/contrib/odbc_1.1.1.tar.gz'
Content type 'application/x-gzip' length 269996 bytes (263 KB)
==================================================
downloaded 263 KB

* installing *source* package ‘odbc’ ...
** package ‘odbc’ successfully unpacked and MD5 sums checked
PKG_CFLAGS=
PKG_LIBS=-lodbc
** libs
(cd cctz && \
make libcctz.a CC="gcc -std=gnu99" CXX="g++ -std=c++11" AR="ar" ARFLAGS=rv)
make[1]: Entering directory `/tmp/RtmpebTEHH/R.INSTALL35511bc7fdc5/odbc/src/cctz'
g++ -std=c++11  -Wall -Iinclude -std=c++11 -pthread  -O -fPIC -MMD  -c -o time_zone_format.o src/time_zone_format.cc
g++ -std=c++11  -Wall -Iinclude -std=c++11 -pthread  -O -fPIC -MMD  -c -o time_zone_if.o src/time_zone_if.cc
g++ -std=c++11  -Wall -Iinclude -std=c++11 -pthread  -O -fPIC -MMD  -c -o time_zone_impl.o src/time_zone_impl.cc
g++ -std=c++11  -Wall -Iinclude -std=c++11 -pthread  -O -fPIC -MMD  -c -o time_zone_info.o src/time_zone_info.cc
src/time_zone_info.cc: In function ‘int32_t cctz::{anonymous}::Decode32(const char*)’:
src/time_zone_info.cc:215:14: error: ‘UINT32_MAX’ was not declared in this scope
src/time_zone_info.cc: In function ‘int64_t cctz::{anonymous}::Decode64(const char*)’:
src/time_zone_info.cc:223:14: error: ‘UINT64_MAX’ was not declared in this scope
src/time_zone_info.cc: In member function ‘cctz::Breakdown cctz::TimeZoneInfo::LocalTime(int64_t, const cctz::TransitionType&) const’:
src/time_zone_info.cc:715:40: error: ‘INT64_MAX’ was not declared in this scope
src/time_zone_info.cc:720:40: error: ‘INT64_MIN’ was not declared in this scope
make[1]: Leaving directory `/tmp/RtmpebTEHH/R.INSTALL35511bc7fdc5/odbc/src/cctz'
make[1]: *** [time_zone_info.o] Error 1
make: *** [cctz/libcctz.a] Error 2
ERROR: compilation failed for package ‘odbc’
* removing ‘/home/bruno/R/x86_64-pc-linux-gnu-library/3.2/odbc’
Warning in install.packages :
  installation of package ‘odbc’ had non-zero exit status

The downloaded source packages are in
	‘/tmp/RtmpO9g6a5/downloaded_packages’

**Comment by jimhester** [comment]
This is likely due to your system compiler being too old. What do you get from `gcc --version` when run from the shell?

**Comment by brunolucian** [comment]
I try gcc -- version and  I get this

gcc (Debian 4.7.2-5) 4.7.2
Copyright (C) 2012 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by jimhester** [comment]
I think you need at least gcc 4.8 for the C++11 features that **odbc** and the cctz and nanodbc libraries use.

**Comment by brunolucian** [comment]
Update for version 4.9 and solved the problem. Thanks!
