### ISSUE TITLE
Could not notify connection observer when connecting

### ISSUE THREAD

**Issue by happyshows** [rstats-db/odbc#103]
### Issue Description and Expected Result

connection showed a warning message when connecting via dsn or connection string. Is this a true issue or something should be ignored? I can still use the connection for query purpose when I trigger the command manually.

However, it caused trouble for me when I try to utilize the "New Connection" feature on Rstudio 1.1 as it keeps reconnecting, see below:

Warning: Could not notify connection observer. nanodbc/nanodbc.cpp:4274: HYC00: [Teradata][ODBC Teradata Driver] Catalogs Not Supported 
> library(DBI)
> con <- dbConnect(odbc::odbc(), "edwapp")
warning messages from top-level task callback '1'
Warning message:
Could not notify connection observer. nanodbc/nanodbc.cpp:4274: HYC00: [Teradata][ODBC Teradata Driver] Catalogs Not Supported  
> library(DBI)
> con <- dbConnect(odbc::odbc(), "edwapp")
warning messages from top-level task callback '1'
Warning message:
Could not notify connection observer. nanodbc/nanodbc.cpp:4274: HYC00: [Teradata][ODBC Teradata Driver] Catalogs Not Supported  
> library(DBI)
> con <- dbConnect(odbc::odbc(), "edwapp")

### Database
Teradata 15.10.0504

### Reproducible Example

<details>
<summary>Session Info</summary>

```r
devtools::session_info()
Session info ------------------------------------------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.3.1 (2016-06-21)
 system   x86_64, darwin13.4.0        
 ui       RStudio (1.1.338)           
 language (EN)                        
 collate  en_US.UTF-8                 
 tz       America/Chicago             
 date     2017-08-22                  

Packages ----------------------------------------------------------------------------------------------------------------------------------
 package  * version    date       source                           
 bit        1.1-12     2014-04-09 CRAN (R 3.3.0)                   
 bit64      0.9-7      2017-05-08 cran (@0.9-7)                    
 blob       1.1.0      2017-07-07 Github (hadley/blob@9dd54d9)     
 DBI      * 0.7-12     2017-08-10 Github (rstats-db/DBI@f8c97f2)   
 devtools   1.12.0     2016-06-24 CRAN (R 3.3.0)                   
 digest     0.6.12     2017-01-27 cran (@0.6.12)                   
 glue     * 1.1.1      2017-06-21 cran (@1.1.1)                    
 hms        0.3        2016-11-22 CRAN (R 3.3.2)                   
 memoise    1.0.0      2016-01-29 CRAN (R 3.3.0)                   
 odbc     * 1.1.1.9000 2017-08-10 Github (rstats-db/odbc@66827c3)  
 Rcpp       0.12.12    2017-07-15 cran (@0.12.12)                  
 rlang      0.1.1.9000 2017-08-10 Github (hadley/rlang@5f0e7ec)    
 tibble     1.3.3.9001 2017-08-10 Github (tidyverse/tibble@cd6337e)
 withr      1.0.2      2016-06-20 CRAN (R 3.3.0)                   
 yaml       2.1.14     2016-11-12 cran (@2.1.14)      
```
</details>

**Comment by jimhester** [comment]
Please update to the latest version of odbc, this should be fixed there.

```r
devtools::update_packages("odbc")
```

**Comment by jimhester** [comment]
See also https://github.com/rstats-db/odbc/issues/98

**Comment by happyshows** [comment]
After I install the odbc_1.1.1.9000, the warning message disappear, however, the Connections Tab still tries to connect multiple times until I stop. Is it a odbc issue or Rstudio IDE issue?

```
> con <- dbConnect(odbc::odbc(), "edw")
> library(DBI)
> con <- dbConnect(odbc::odbc(), "edw")
> library(DBI)
> con <- dbConnect(odbc::odbc(), "edw")
> library(DBI)
> con <- dbConnect(odbc::odbc(), "edw")
> library(DBI)
> con <- dbConnect(odbc::odbc(), "edw")
> library(DBI)
> con <- dbConnect(odbc::odbc(), "edw")
> library(DBI)
> con <- dbConnect(odbc::odbc(), "edw")
```

**Comment by jimhester** [comment]
That is an IDE issue, it is likely fixed in the daily.

**Comment by happyshows** [comment]
It is, thanks.
