### ISSUE TITLE
Allow to filter the catalogue in connection tab - Feature Request

### ISSUE THREAD

**Issue by happyshows** [rstats-db/odbc#104]
There are thousands of schemas in the database I'm connecting to, however the connection tab only shows 20? alphabetically each time. If I need to browse the schema I need, I'll have to click 100 times of "Show More".

So I hope there would be some additional parameter to allow me to filter / regex matching some schema names that I'm interested to know. Or just match the exact schema name I configured in dsn to establish connection?

**Comment by jimhester** [comment]
This is an IDE issue, so you will need to open an issue at the support forum https://support.rstudio.com/hc/en-us. I think there may be an option you can use to adjust how many items are fetched, but I do not know for sure.

You can use `dbListTables(con, schema_name = 'xyz%')` where `%` is a wildcard character to search schemas from the R console.

**Comment by happyshows** [comment]
k thanks.
