### ISSUE TITLE
installation fails with compilers that don't understand `-std=c++11`

### ISSUE THREAD

**Issue by kevinushey** [rstats-db/odbc#105]
It looks like the C++ standard used during compilation of `cctz` is hard-coded here as `c++11`:

https://github.com/rstats-db/odbc/blob/12a44e1b3447a388df283ee97aa02c3393e0d7cf/src/cctz/Makefile#L24

Is there any chance this could be relaxed to `c++0x`, for older compilers that implement the subset of C++11 features required for this library? Or are relatively modern compilers required here?

**Comment by kevinushey** [comment]
Some testing on my Ubuntu box:

- gcc-4.4:  ❌
- gcc-4.6:  ❌
- gcc-4.8:  ✅

So this library does seem to require a relatively new compiler.

This is going to be problematic in enterprise environments -- I think this implies that odbc will not work by default on e.g. RHEL5 or RHEL6, where gcc-4.4 is still the default compiler.

**Comment by jimhester** [comment]
Yes, using the Developer Toolset is the intention if someone is stuck with non-C++11 compliant compilers.

**Comment by smach** [comment]
Is this why I'm getting this error message when trying to install GitHub version of the package on a Windows system?

```
Warning: running command 'make -f "Makevars.win" -f "C:/PROGRA~1/R/R-34~1.1/etc/i386/Makeconf" -f "C:/PROGRA~1/R/R-34~1.1/share/make/winshlib.mk" CXX='$(CXX11) $(CXX11STD)' CXXFLAGS='$(CXX11FLAGS)' CXXPICFLAGS='$(CXX11PICFLAGS)' SHLIB_LDFLAGS='$(SHLIB_CXX11LDFLAGS)' SHLIB_LD='$(SHLIB_CXX11LD)' SHLIB="odbc.dll" ' had status 2
ERROR: compilation failed for package 'odbc'
```

If so, what should I do on my Windows system to fix? (CRAN version installs fine.)

**Comment by jimhester** [comment]
No, Windows should be fine, you just have to ensure you have Rtools installed

**Comment by smach** [comment]
@jimhester Thank you. I had an old version of Rtools, but hadn't updated after updating R. Works fine now.
