### ISSUE TITLE
object '_odbc_bigint_mappings' not found  (ok in 1.1.1, error in 1.1.1.9000)

### ISSUE THREAD

**Issue by jonspring** [rstats-db/odbc#110]
### Issue Description and Expected Result
I can connect to SQL Server using ODBC 1.1.1 from CRAN using this code:
```r 
library(odbc)
library(DBI)
con <- dbConnect(odbc::odbc(),
                 driver = "SQL Server",
                 # bigint = bigint,
                 server = server_name,
                 database = db_name,
                 port = 1433
                 )
```
But when I run the same code using 1.1.1.9000, it throws an error:

<b>Error in bigint_mappings() : object '_odbc_bigint_mappings' not found</b>

<summary>Session Info</summary>

```r
devtools::session_info()
#> R version 3.4.1 (2017-06-30)
Platform: i386-w64-mingw32/i386 (32-bit)
Running under: Windows 7 (build 7601) Service Pack 1

...

other attached packages:
[1] odbc_1.1.1.9000 dbplyr_1.1.0    DBI_0.7    
```
</details>

**Comment by jimhester** [comment]
Make sure you restart R before trying to install and run the new version.
