### ISSUE TITLE
bigint argument ignored. (R 3.3.2, ODBC driver from github, PostgreSQL server)

### ISSUE THREAD

**Issue by ocschwar** [rstats-db/odbc#113]
Connections set with bigint="character" or "integer" continue to return bigint columns as integer64.

### Database
PostgreSQL 9.5

### Reproducible Example
The class remains "integer64"
```r
library(odbc)
library(DBI)
con <- DBI::dbConnect(odbc::odbc(), Driver = "psqlodbcw.so", 
                     UID = "omri", PWD = "ELIDED",
Driver = "PostgreSQL ANSI",
                       Server = "ELIDEeast-1.rds.amazonaws.com", 
                       database = "wind_farm" , bigint="character")
class(DBI::dbReadTable(con,"project_version")$proj_id)
```
-->

<details>
<summary>Session Info</summary>

```r
> devtools::session_info()
Session info ----------------------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.3.2 (2016-10-31)
 system   x86_64, linux-gnu           
 ui       RStudio (99.9.9)            
 language en_US                       
 collate  en_US.UTF-8                 
 tz       <NA>                        
 date     2017-09-25                  

Packages --------------------------------------------------------------------------------------------------------------
 package     * version    date       source                         
 base        * 3.3.2      2016-11-02 local                          
 bit           1.1-12     2014-04-09 CRAN (R 3.3.2)                 
 bit64         0.9-7      2017-05-08 CRAN (R 3.3.2)                 
 blob          1.1.0      2017-06-17 CRAN (R 3.3.2)                 
 curl          2.8.1      2017-07-21 cran (@2.8.1)                  
 data.table    1.10.4     2017-02-01 cran (@1.10.4)                 
 datasets    * 3.3.2      2016-11-02 local                          
 DBI           0.7        2017-06-18 cran (@0.7)                    
 devtools      1.13.3     2017-08-02 cran (@1.13.3)                 
 digest        0.6.12     2017-01-27 CRAN (R 3.3.2)                 
 git2r         0.19.0     2017-07-19 cran (@0.19.0)                 
 graphics    * 3.3.2      2016-11-02 local                          
 grDevices   * 3.3.2      2016-11-02 local                          
 hms           0.3        2016-11-22 CRAN (R 3.3.2)                 
 httr          1.3.1      2017-08-20 cran (@1.3.1)                  
 magrittr      1.5        2014-11-22 CRAN (R 3.3.2)                 
 maps          3.2.0      2017-06-08 cran (@3.2.0)                  
 memoise       1.1.0      2017-04-21 CRAN (R 3.3.2)                 
 methods     * 3.3.2      2016-11-02 local                          
 odbc          1.1.1.9000 2017-09-25 Github (rstats-db/odbc@02fd6bb)
 plotrix       3.6-6      2017-08-16 cran (@3.6-6)                  
 png           0.1-7      2013-12-03 cran (@0.1-7)                  
 R6            2.2.2      2017-06-17 cran (@2.2.2)                  
 Rcpp          0.12.12    2017-07-15 cran (@0.12.12)                
 REhedge       0.2.13     2017-08-29 local                          
 rlang         0.1.2      2017-08-09 cran (@0.1.2)                  
 RPostgreSQL   0.6-2      2017-06-24 cran (@0.6-2)                  
 stats       * 3.3.2      2016-11-02 local                          
 tibble        1.3.4      2017-08-22 cran (@1.3.4)                  
 tools         3.3.2      2016-11-02 local                          
 utils       * 3.3.2      2016-11-02 local                          
 withr         2.0.0      2017-07-28 cran (@2.0.0)                  
 yaml          2.1.14     2016-11-12 cran (@2.1.14)                 
> ```
</details>

**Comment by jimhester** [comment]
I can't reproduce this, can you use an example I can potentially reproduce? e.g. try running the following (substituting your connection information as needed)

``` r
library(DBI)
con <- dbConnect(odbc::odbc(), "PostgreSQL")
str(dbGetQuery(con, "SELECT 10000000000000000 as x"))
#> 'data.frame':    1 obs. of  1 variable:
#>  $ x:integer64 10000000000000000

con_c <- dbConnect(odbc::odbc(), "PostgreSQL", bigint = "character")
str(dbGetQuery(con_c, "SELECT 10000000000000000 as x"))
#> 'data.frame':    1 obs. of  1 variable:
#>  $ x: chr "10000000000000000"

con_d <- dbConnect(odbc::odbc(), "PostgreSQL", bigint = "numeric")
str(dbGetQuery(con_d, "SELECT 10000000000000000 as x"))
#> 'data.frame':    1 obs. of  1 variable:
#>  $ x: num 1e+16
```

**Comment by ocschwar** [comment]
Now I am having trouble reproducing it in Linux. Conversions work. HOWEVER.
Windows, with the latest R Studio, I get this:

> con <- DBI::dbConnect(drv = odbc::odbc(), bigint = "integer",
+                       UID = user, PWD = password, Server = host,
+                       database = dbname, Driver = Driver)
> str(dbGetQuery(con, "SELECT 10000000000000000 as x"))
'data.frame':    1 obs. of  1 variable:
 $ x:integer64 10000000000000000 
> 
> con <- DBI::dbConnect(drv = odbc::odbc(),
+                       UID = user, PWD = password, Server = host,
+                       database = dbname, Driver = Driver)
> str(dbGetQuery(con, "SELECT 10000000000000000 as x"))
'data.frame':    1 obs. of  1 variable:
 $ x:integer64 10000000000000000 
> 
> con <- DBI::dbConnect(drv = odbc::odbc(), bigint = "character",
+                       UID = user, PWD = password, Server = host,
+                       database = dbname, Driver = Driver)
> str(dbGetQuery(con, "SELECT 10000000000000000 as x"))
'data.frame':    1 obs. of  1 variable:
 $ x:integer64 10000000000000000 
> 
> 
> con <- DBI::dbConnect(drv = odbc::odbc(), bigint = "numeric",
+                       UID = user, PWD = password, Server = host,
+                       database = dbname, Driver = Driver)
> str(dbGetQuery(con, "SELECT 10000000000000000 as x"))
'data.frame':    1 obs. of  1 variable:
 $ x:integer64 10000000000000000 
>

**Comment by jimhester** [comment]
Please make sure you install the devel version of odbc on windows when it is not already loaded, and that you restart R afterwards.

**Comment by ocschwar** [comment]
str(DBI::dbGetQuery(con, "SELECT 10000000000000000 as x"))
'data.frame':    1 obs. of  1 variable:
 $ x:integer64 10000000000000000 
> str(con)
Formal class 'PostgreSQL' [package ".GlobalEnv"] with 4 slots
  ..@ ptr     :<externalptr> 
  ..@ quote   : chr "\""
  ..@ info    :List of 13
  .. ..$ dbname               : chr "wind_farm"
  .. ..$ dbms.name            : chr "PostgreSQL"
  .. ..$ db.version           : chr "9.5.4"
  .. ..$ username             : chr "christian"
  .. ..$ host                 : chr ""
  .. ..$ port                 : chr ""
  .. ..$ sourcename           : chr ""
  .. ..$ servername           : chr "production-instance0.ch66mbrytjgc.us-east-1.rds.amazonaws.com"
  .. ..$ drivername           : chr "PSQLODBC30A.DLL"
  .. ..$ odbc.version         : chr "03.80.0000"
  .. ..$ driver.version       : chr "09.06.0500"
  .. ..$ odbcdriver.version   : chr "03.51"
  .. ..$ supports.transactions: logi TRUE
  .. ..- attr(*, "class")= chr [1:3] "PostgreSQL" "driver_info" "list"
  ..@ encoding: chr ""
>

**Comment by ocschwar** [comment]
This is the most recent version of the driver that I could find.

**Comment by jimhester** [comment]
I cannot reproduce this error, I think it must be an installation issue.
