### ISSUE TITLE
Unable to read temp tables

### ISSUE THREAD

**Issue by nwstephens** [rstats-db/odbc#114]
I can create temp tables in Oracle and verify they exist, but I cannot read temp tables in Oracle.

```
library(odbc)
library(DBI)
odbcOracleCon <- dbConnect(odbc(),Driver = "Oracle",Host = "",SVC = "",Uid = "",PWD = "",Port = 1521)
dbRemoveTable(odbcOracleCon, "tempmtcars")
dbWriteTable(odbcOracleCon, "tempmtcars", mtcars, temporary = TRUE)
dbExistsTable(odbcOracleCon, "tempmtcars")
dbReadTable(odbcOracleCon, "temptcars")
```

**Comment by jimhester** [comment]
temp tables in Oracle work different than in other databases than SQL Server (https://stackoverflow.com/a/2671612/2055486). I don't think there is anything we can do about this.

**Comment by nwstephens** [comment]
Jim, that post is talking about creating temp tables. I'm talking about reading a temp table. I cannot read a temp table. For example, these statements do now work for me:
```
> library(odbc)
> library(DBI)
> odbcOracleCon <- dbConnect(odbc(),Driver = "Oracle",Host = "sol-eng-oracle-two.cihykudhzbgw.us-west-2.rds.amazonaws.com",SVC = "airontim",Uid = "rstudioadmin",PWD = "ABCd4321",Port = 1521)
> dbReadTable(odbcOracleCon, "temptcars")
Error in new_result(connection@ptr, statement) : 
  nanodbc/nanodbc.cpp:1344: HY000: ORA-00942: table or view does not exist
```

**Comment by jimhester** [comment]
There was a typo in the original code `temptcars` should have been `tempmtcars` in the last line. With that change the code works without an issue, so I am closing this.
