### ISSUE TITLE
Installation fails on macOS El Capitan, R 3.3.1

### ISSUE THREAD

**Issue by joranE** [rstats-db/odbc#12]
I'd like to start experimenting with this project, but I'm having some difficulty installing **odbc** from github on macOS. It appears to be some C++/Rcpp configuration issue on my system, but I can't quite figure out what to update.

When I run:

```r
devtools::install_github("rstats-db/odbc")

* installing *source* package ‘odbc’ ...
Found pkg-config cflags and libs!
Using PKG_CFLAGS=-I/usr/local/include
Using PKG_LIBS=-L/usr/local/lib  -liodbc -liodbcinst
** libs
clang++ -std=c++11 -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG  -I/usr/local/include -I/usr/local/include/freetype2 -I/opt/X11/include -I"/Users/joranelias/RLib/Rcpp/include" -I"/Users/joranelias/RLib/BH/include"  -I. -std=c++14 -DNANODBC_USE_BOOST_CONVERT -DNANODBC_ODBC_VERSION=SQL_OV_ODBC3  -fPIC  -Wall -mtune=core2 -g -O2 -c RcppExports.cpp -o RcppExports.o
error: invalid value 'c++14' in '-std=c++14'
make: *** [RcppExports.o] Error 1
ERROR: compilation failed for package ‘odbc’
* removing ‘/Users/joranelias/RLib/odbc’
Error: Command failed (1)
```

I get that error, which I presume means I need to update something on my system with regards to Rcpp, perhaps, but I'm just not sure what.

I have Rcpp 0.12.7 and BH 1.60.0-2. Do I need to recompile them, or something else from source?

<details>
<summary>Session Info</summary>

```r
> devtools::session_info()
#> R version 3.3.1 (2016-06-21)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: OS X 10.11.5 (El Capitan)

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] httr_1.2.1      R6_2.1.2        tools_3.3.1     withr_1.0.1     curl_1.1        memoise_1.0.0   git2r_0.15.0   
[8] digest_0.6.9    devtools_1.12.0
```
</details>

**Comment by jimhester** [comment]
You must be using a compiler version which does not support c++14 extensions. The need for c++14 was actually trivial in the nanodbc library, so I just removed it with https://github.com/rstats-db/odbc/commit/8426669546623837a043d9efcba6ab049931b33f.

Please try installing the lastest version and let me know if it works for you.

**Comment by joranE** [comment]
That worked fine, many thanks for the speedy response. Must be a different compiler version in El Capitan, maybe I need to update my xcode tools. If you want me to check on anything on my system to nail down the specific issue feel free to ask, although I may need fairly specific directions.

**Comment by jimhester** [comment]
No it is fine, a future goal is to support C++03, so getting part of the way there now is good.
