### ISSUE TITLE
source() + dbSendQuery() Returns Incorrect Results - Solved with: dbExecute()

### ISSUE THREAD

**Issue by jtelleriar** [rstats-db/odbc#123]
### Issue Description and Expected Result
When used source() with dbSendQuery(), wrong results are obtained from the Database.

### Database
MariaDB

### Solution
It was solved by means of using source() + dbExecute(), instead of dbSendQuery().

### Question
Although not Standard, ¿Shall dbSendQuery() default behavior be modified?.

**Comment by jimhester** [comment]
Sorry you have not given enough details to see what the problem is, and `dbSendQuery()` and `dbExecute()` do different things, they are not drop in replacements for each other. If you have further details I will re-open this.
