### ISSUE TITLE
NeedsCompilation missing from DESCRIPTION?

### ISSUE THREAD

**Issue by mingwandroid** [rstats-db/odbc#124]
### Issue Description and Expected Result

I am trying to use `conda skeleton cran https://github.com/rstats-db/odbc` to make a recipe to make a `conda` package for this, and our skeleton code only adds a dependency on compilation tools (GNU make, compilers, autotools) when it reads `NeedsCompilation` in `DESCRIPTION`.

Would it be possible to add this?

**Comment by mingwandroid** [comment]
A reference for this: https://cran.r-project.org/doc/manuals/r-devel/R-exts.html

> The ‘NeedsCompilation’ field should be set to "yes" if the package contains code which to be compiled, otherwise "no" (when the package could be installed from source on any platform without additional tools). This is used by install.packages(type = "both") in R >= 2.15.2 on platforms where binary packages are the norm: it is normally set by R CMD build or the repository assuming compilation is required if and only if the package has a src directory.

**Comment by jimhester** [comment]
> it is normally set by R CMD build or the repository assuming compilation is required if and only if the package has a src directory

`NeedsCompilation` is set automatically for _built_ packages created with `R CMD build`, the packages in most repositories are source packages that have not yet been built. As another example these packages often don't have a `Maintainer` or `Author` field either, as these are created from `Authors@R`.

If you are trying to make binaries you need to use the built package from CRAN e.g. https://cran.r-project.org/src/contrib/odbc_1.1.3.tar.gz, which does contain `NeedsCompilation`.

If you do want to build off of development source repositories such as this one you will need to first build the package yourself before creating the binary.

```shell
R CMD build . && R CMD INSTALL --build odbc*tar.gz
```

**Comment by mingwandroid** [comment]
Ah ok thanks for the details. Out of interest do you know what compatibility guarantees there are for packages that do not require compilation both across versions and across operating systems?

Sorry for the random question!

**Comment by jimhester** [comment]
I am not sure there are any explicit guarantees given anywhere. But generally R only binary packages built with the same minor version number should be compatible on the same OS.

In general I don't think cross platform compatibility exists for R binaries, with or without compiled code. Although I would guess you could probably load most R-only binaries on most non-windows OSs without issue.
