### ISSUE TITLE
Vague error connecting to SQL Server: "Error in odbc_connect(connection_string) : nanodbc.cpp:895"

### ISSUE THREAD

**Issue by dgrtwo** [rstats-db/odbc#16]
Trying to connect to a SQL Server instance gives me a cryptic error: 

    Error in odbc_connect(connection_string) : nanodbc.cpp:895:    �:

### Database

SQL Server 2012 (and SQL Server 2016 throws the same error)

### Reproducible Example

I get an error as soon as I try to connect (in this case to the [example AdventureWorks database](http://sqlblog.com/blogs/jamie_thomson/archive/2012/11/30/olympics-data-available-for-all-on-windows-azure-sql-database.aspx)):

```r
library(DBI)
con <- dbConnect(odbc::odbc(),
                 driver = "FreeTDS",
                 database = "AdventureWorks2012",
                 uid = "sqlfamily",
                 pwd = "sqlf@m1ly",
                 host = "mhknbn2kdz.database.windows.net",
                 port = 1433)

Error in odbc_connect(connection_string) : nanodbc.cpp:895:    �:
```

(That one line, including the �, is the full error, I haven't gotten it to print out more). 

I've tried some variations on this connection string, putting the data in odbc.ini, and gotten this error consistently (and the same on my own database). I've also been able to connect to my own database through isql (in unix-odbc) without a problem, so I don't think it's a problem with my driver setup.

<details>
<summary>Session Info</summary>

```r
R version 3.3.0 (2016-05-03)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: OS X 10.11.5 (El Capitan)

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] DBI_0.5-12

loaded via a namespace (and not attached):
[1] odbc_0.0.0.9000 tools_3.3.0     Rcpp_0.12.8    
```
</details>

**Comment by dgrtwo** [comment]
I should note that changing the driver to something nonsensical (e.g. "NotADriver") does change the error message:

    Error in odbc_connect(connection_string) : 
      nanodbc.cpp:895: 00000: [iODBC][Driver Manager]dlopen(NotADriver, 6): image not found                                                                                                                                                                                                                                                                                                                                                                                                                                                                   

However, changing anything else (the database, the password, the port) leads to the same error message.

**Comment by jimhester** [comment]
Yes not very useful error message for sure. 

I can successfully connect using the following connection settings. Things I changed were the driver from "FreeTDS" to the name of the library `libtdsodbc.so` and using `Server` rather than `Host`. The driver setting needs to be the library name unless you have setup a driver entry in your system or user`odbcinst.ini` file. If the library is not on the `LD_LIBRARY_PATH` you need to give the full path to the library, not just the name.

```r
con <- dbConnect(odbc::odbc(),
                 driver = "libtdsodbc.so",
                 database = "AdventureWorks2012",
                 uid = "sqlfamily",
                 pwd = "sqlf@m1ly",
                 Server = "mhknbn2kdz.database.windows.net",
                 port = 1433)
```

It looks like you are using iODBC rather than unix odbc, which may be the cause of the obtuse error message. I would recommend using unix odbc if possible, that is what I have been developing against.

**Comment by dgrtwo** [comment]
Hmm, I'm getting the exact same error with those changes.

I thought I was using unix-odbc (it's what I installed with brew). What's iODBC? (isql as I'm using it is a unixODBC tool):

![image](https://cloud.githubusercontent.com/assets/994718/20809007/b257d076-b7d2-11e6-87ee-8e3267b028c9.png)

Incidentally, I think the reason I can use FreeTDS as the argument is I have this in my odbcinst.ini:

```
[FreeTDS]
Description=FreeTDS Driver for Linux & MSSQL on Win32
Driver=/usr/local/lib/libtdsodbc.so
Setup=/usr/local/lib/libtdsodbc.so
UsageCount=1

```

**Comment by jimhester** [comment]
Looks like issue is freeTDS is linked against unixodbc, but you have iODBC in your library path. You should be able to fix it with the following.

```shell
brew unlink libiodbc
brew link unixodbc
```
Then re-install the odbc package.

I can reproduce your issue (including terrible error message) if I do the opposite (link libiodbc and unlink unixodbc). Let me know if this fixes things.

**Comment by dgrtwo** [comment]
Unfortunately not: I don't seem to have libiodbc installed through brew:

    nyc-drobinson-idk:Repositories drobinson$ brew unlink libiodbc
        Error: No such keg: /usr/local/Cellar/libiodbc

(I confirmed there's nothing like libiodbc in my Cellar). I do have libiodbc lib files in both my /usr/local/lib and my /usr/lib. I moved all the libs out of the /usr/local/lib directory and reinstalled odbc (and restarted R to be safe), but got the same error.

I find I cannot move or remove any of the files in /usr/lib even with root (and it seems to me like I shouldn't have to?)

Incidentally, what indicates that the problem is iODBC related?

**Comment by jimhester** [comment]
> Error in odbc_connect(connection_string) : 
  nanodbc.cpp:895: 00000: [iODBC][Driver Manager]dlopen(NotADriver, 6): image not found

------------------------------^
That would be unixodbc if odbc was compiled against unixodbc.

Additionally when you compile the package if you look near the top it should say something like (probably with different paths)

```
Found pkg-config cflags and libs!
Using PKG_CFLAGS=-I/usr/local/Cellar/libiodbc/3.52.12/include
Using PKG_LIBS=-L/usr/local/Cellar/libiodbc/3.52.12/lib  -liodbc -liodbcinst
```
Whereas with unixodbc they would be
```
Using PKG_CFLAGS=
USING PKG_LIBS=-lodbc
```

Also if you run the following you will see that libtdsodbc is linked against unixodbc, which is why you are getting the issue.
```shell
otool -L /usr/local/lib/libtdsodbc.so
/usr/local/lib/libtdsodbc.so:
        /usr/local/opt/openssl/lib/libssl.1.0.0.dylib (compatibility version 1.0.0, current version 1.0.0)
        /usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib (compatibility version 1.0.0, current version 1.0.0)
        /usr/local/opt/unixodbc/lib/libodbcinst.2.dylib (compatibility version 3.0.0, current version 3.0.0)
        /usr/lib/libiconv.2.dylib (compatibility version 7.0.0, current version 7.0.0)
        /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1238.0.0)
```

The other thing you may want to look for is `iodbc-config`, if this is found on the path it takes precedence, you may have to move or rename it.

**Comment by dgrtwo** [comment]
You are right that I had iodbc-config on the path: I renamed it and reinstalled, but the error continues.

Pointing me to the installation messages helps, though. When I install, below is the message I get, which includes a note about "No package 'odbc' found," which I'm guessing is the problem.

I'll be away from this computer for the rest of tonight, but will work on fixing that tomorrow morning!

```
> devtools::install_github("rstats-db/odbc")
Downloading GitHub repo rstats-db/odbc@master
from URL https://api.github.com/repos/rstats-db/odbc/zipball/master
Installing odbc
'/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file --no-environ  \
  --no-save --no-restore --quiet CMD INSTALL  \
  '/private/var/folders/1d/gggvxyc548d357l5lrv1dz6w5nxxzg/T/RtmpOFC6VQ/devtoolsa8c36e9dbb11/rstats-db-odbc-42846d5'  \
  --library='/Users/drobinson/Library/R/3.3/library' --install-tests 

* installing *source* package ‘odbc’ ...
Package odbc was not found in the pkg-config search path.
Perhaps you should add the directory containing `odbc.pc'
to the PKG_CONFIG_PATH environment variable
No package 'odbc' found
Package odbc was not found in the pkg-config search path.
Perhaps you should add the directory containing `odbc.pc'
to the PKG_CONFIG_PATH environment variable
No package 'odbc' found
Using PKG_CFLAGS=
Using PKG_LIBS=-lodbc
** libs
clang++ -std=c++11 -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG  -I/usr/local/include -I/usr/local/include/freetype2 -I/opt/X11/include -I"/Users/drobinson/Library/R/3.3/library/Rcpp/include" -I"/Users/drobinson/Library/R/3.3/library/BH/include"  -I. -DNANODBC_USE_BOOST_CONVERT -DNANODBC_ODBC_VERSION=SQL_OV_ODBC3 -fPIC  -fPIC  -Wall -mtune=core2 -g -O2 -c RcppExports.cpp -o RcppExports.o
clang++ -std=c++11 -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG  -I/usr/local/include -I/usr/local/include/freetype2 -I/opt/X11/include -I"/Users/drobinson/Library/R/3.3/library/Rcpp/include" -I"/Users/drobinson/Library/R/3.3/library/BH/include"  -I. -DNANODBC_USE_BOOST_CONVERT -DNANODBC_ODBC_VERSION=SQL_OV_ODBC3 -fPIC  -fPIC  -Wall -mtune=core2 -g -O2 -c connection.cpp -o connection.o
clang++ -std=c++11 -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG  -I/usr/local/include -I/usr/local/include/freetype2 -I/opt/X11/include -I"/Users/drobinson/Library/R/3.3/library/Rcpp/include" -I"/Users/drobinson/Library/R/3.3/library/BH/include"  -I. -DNANODBC_USE_BOOST_CONVERT -DNANODBC_ODBC_VERSION=SQL_OV_ODBC3 -fPIC  -fPIC  -Wall -mtune=core2 -g -O2 -c nanodbc.cpp -o nanodbc.o
clang++ -std=c++11 -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG  -I/usr/local/include -I/usr/local/include/freetype2 -I/opt/X11/include -I"/Users/drobinson/Library/R/3.3/library/Rcpp/include" -I"/Users/drobinson/Library/R/3.3/library/BH/include"  -I. -DNANODBC_USE_BOOST_CONVERT -DNANODBC_ODBC_VERSION=SQL_OV_ODBC3 -fPIC  -fPIC  -Wall -mtune=core2 -g -O2 -c odbc_connection.cpp -o odbc_connection.o
clang++ -std=c++11 -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG  -I/usr/local/include -I/usr/local/include/freetype2 -I/opt/X11/include -I"/Users/drobinson/Library/R/3.3/library/Rcpp/include" -I"/Users/drobinson/Library/R/3.3/library/BH/include"  -I. -DNANODBC_USE_BOOST_CONVERT -DNANODBC_ODBC_VERSION=SQL_OV_ODBC3 -fPIC  -fPIC  -Wall -mtune=core2 -g -O2 -c result.cpp -o result.o
clang++ -std=c++11 -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -single_module -multiply_defined suppress -L/Library/Frameworks/R.framework/Resources/lib -L/usr/local/lib -o odbc.so RcppExports.o connection.o nanodbc.o odbc_connection.o result.o -lodbc -F/Library/Frameworks/R.framework/.. -framework R -Wl,-framework -Wl,CoreFoundation
installing to /Users/drobinson/Library/R/3.3/library/odbc/libs
** R
** tests
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
* DONE (odbc)

```

**Comment by jimhester** [comment]
That last install linked to `-lodbc` which is unixodbc, so it should now be working, you may have to restart R to ensure the library is loaded though.

**Comment by jimhester** [comment]
@dgrtwo Were you able to get this working?

**Comment by dgrtwo** [comment]
I did just now (both to the test db and to my company's)- great! Thank you.

**Comment by jimhester** [comment]
Great, thanks!

**Comment by perrystephenson** [comment]
Just to add a bit of confusion to the mix... 

I was having the same error connecting to Teradata. Following the debugging ideas above, (I think) I figured out the Teradata ODBC drivers use iODBC rather than unixODBC. I installed iODBC and then did the unlink/link thing in homebrew, reinstalled the odbc package, and everything started working! The error messages using iODBC are much better as well.

Not sure if this will help you guys developing the package, but if anyone else is having issues connecting to Teradata you might want to try doing the opposite of everything mentioned above (i.e. use iODBC instead of unixODBC).

**Comment by happyshows** [comment]
@perrystephenson could you share the connection string used via your approach? I'm having trouble to connect via either ways.

**Comment by IrinaMax** [comment]
Can somebody help? I have error : 
`Error: nanodbc/nanodbc.cpp:950: 01000: [unixODBC][Driver Manager]Can't open lib 'SQLServer' : file not found 
`
All odbc manager and drivers all installed from the brew and I also try `devtools::install_github("rstats-db/odbc")` and It looks all are good! but still not connected :(

**Comment by jimhester** [comment]
@IrinaMax the `file not found` is likely a shared library dependency that cannot be found. Running `otool -L /usr/local/lib/libtdsodbc.so` (or the shared library of the driver you are using) may reveal which dependency is missing.

**Comment by rishabhack** [comment]
@jimhester 
Sir I am facing this issue. This issue is occurred in live db connection not in local PC. 
As I am using windows OS. FreeTDS does not work here.
I had installed all relevant drivers and tried and searched but didn't found solution with ODBC/RODBC.
Is there is any solution for windows Live DB Connection ? This is an very common problem.
Or any reason why this occur?  
Details :
> library(DBI)
> con <- dbConnect(odbc::odbc(), .connection_string = "Driver={ODBC Driver 13 for SQL Server};Server=10.68.82.72;
+ Port=1433;
+ Database=rmsaview;
+ UID=sa;
+ Password=nic;
+  ")
Error: nanodbc/nanodbc.cpp:950: 28000: [Microsoft][ODBC Driver 13 for SQL Server][SQL Server]Login failed for user 'sa'.

**Comment by AthenaArtFinance** [comment]
> otool -L /usr/local/lib/libtdsodbc.so

Hi @jimhester ,

This doesn't work for me. I receive the same error when i try to connect to SQL Server on Linux.

`Error: nanodbc/nanodbc.cpp:950: 01000: [unixODBC][Driver Manager]Can't open lib '/root/sqlserver/sqlserver/bin/lib/libsqlserverodbc_sb64.so' : file not found`

My odbcinst.ini file has it correctly mapped
[SQLServer Driver]
Driver = /root/sqlserver/bin/lib/libsqlserverodbc_sb64.so


Any leads on this?
