### ISSUE TITLE
Unable to connect to MSSQL on Ubuntu

### ISSUE THREAD

**Issue by barnettjacob** [rstats-db/odbc#21]
### Issue Description and Expected Result
Unable to create connection to MSSQL database from ubuntu machine. I have unixODBC and FreeTDS and have odbc.ini and odbcinst.ini configured as per the readme. Any help would be massively appreciated.

For reproducibility I'm using the `rocker-org` docker image `ropensci` although I also get the same result on a standard Ubuntu config (14.04).

### Database
SQL Server 2014 (12.0.5000.0)

### Example
```
> library(DBI)
> con <- dbConnect(odbc::odbc(),
+                  driver = "FreeTDS",
+                  database = "xxxxx",
+                  uid = "xxxxxxxxxxxx",
+                  pwd = "xxxxxxxxxxxxxxxx",
+                  host = "warehousesql.xxxxxxxxxxxxx.com")
Error in odbc_connect(connection_string) : 
  nanodbc.cpp:950: 08001: [unixODBC][FreeTDS][SQL Server]Unable to connect to data source 
```
```
> library(DBI)
> con <- dbConnect(odbc::odbc(), "warehouse")
Error in odbc_connect(connection_string) : 
  nanodbc.cpp:950: 08001: [unixODBC][FreeTDS][SQL Server]Unable to connect to data source 
```

```
Session info ------------------------------------------------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.3.2 (2016-10-31)
 system   x86_64, linux-gnu           
 ui       RStudio (1.0.136)           
 language (EN)                        
 collate  en_US.UTF-8                 
 tz       <NA>                        
 date     2017-01-11                  

Packages ----------------------------------------------------------------------------------------------------------------------------------------
 package    * version    date       source                         
 curl         2.3        2016-11-24 CRAN (R 3.3.2)                 
 DBI        * 0.5-14     2017-01-11 Github (rstats-db/DBI@8afe845) 
 devtools     1.12.0     2016-12-05 CRAN (R 3.3.2)                 
 digest       0.6.11     2017-01-03 CRAN (R 3.3.2)                 
 git2r        0.18.0     2017-01-01 CRAN (R 3.3.2)                 
 httr         1.2.1      2016-07-03 CRAN (R 3.3.2)                 
 memoise      1.0.0      2016-01-29 CRAN (R 3.3.2)                 
 odbc       * 0.0.0.9000 2017-01-11 Github (rstats-db/odbc@2d187b3)
 R6           2.2.0      2016-10-05 CRAN (R 3.3.2)                 
 Rcpp         0.12.8     2016-11-17 cran (@0.12.8)                 
 rstudioapi   0.6        2016-06-27 CRAN (R 3.3.2)                 
 withr        1.0.2      2016-06-20 CRAN (R 3.3.2)  
```
Config Files:
```
/etc$ cat odbc.ini
[warehouse]
Driver 		= FreeTDS
Server 		= warehousesql.xxxxxxxxx.com
UserName 	= xxxxxxxxxxxxx
Password	= xxxxxxxxxxxxx
Database	= xxxxxxxxx 
```
```
/etc$ cat odbcinst.ini
[FreeTDS]
Description = v0.91 with protocol v7.2
Driver = /usr/lib/x86_64-linux-gnu/odbc/libtdsodbc.so

**Comment by jimhester** [comment]
The arguments to `dbConnect()` need to be consistent with the variable names your driver / dbms expects.

It looks like you have a DSN setup, can you connect using just the DSN name?

```r
con <- dbConnect(odbc::odbc(), dsn = "FreeTDS")
```

**Comment by barnettjacob** [comment]
Hi Jim, thanks for the speedy response! With that I get a different error:

```
> con <- dbConnect(odbc::odbc(), dsn = "FreeTDS")
Error in odbc_connect(connection_string) : 
  nanodbc.cpp:950: IM002: [unixODBC][Driver Manager]Data source name not found, and no default driver specified 
```
My understanding is that the DSN is contained in `odbc.ini` and it isn't important what the groups are called. I've also tried changing the group name in odbc.ini to `FreeTDS` and get the same result as the one above when using and calling the name `warehouse`.

Thanks,

**Comment by jimhester** [comment]
From the error I think the DSN is not installed in the expected system DSN directory.

Could you try running the following in your shell to see where unixodbc is looking for your system config files (odbcinst is a program that should be installed with unixodbc, but may not be on your PATH).

```shell
odbcinst -j
```

In particular the `SYSTEM DATA SOURCES` file should be where your `odbc.ini` file is installed, I expect it is different than the files you have configured.

**Comment by barnettjacob** [comment]
From that I get:
```
~$ odbcinst -j
unixODBC 2.3.1
DRIVERS............: /etc/odbcinst.ini
SYSTEM DATA SOURCES: /etc/odbc.ini
FILE DATA SOURCES..: /etc/ODBCDataSources
USER DATA SOURCES..: /home/rstudio/.odbc.ini
SQLULEN Size.......: 8
SQLLEN Size........: 8
SQLSETPOSIROW Size.: 8
```
I tried moving the `ini` files to `/home/rstudio` without success.

**Comment by jimhester** [comment]
Sorry I misread your initial post, you have the config files in the right place. I think if you use the name `server` in place of `host` in your config files or the example it should work.

**Comment by barnettjacob** [comment]
Unfortunately not - it was always `server` in the config and I changed `host` in the example without success.

**Comment by jimhester** [comment]
Can you connect to the database with the following in the shell?

```shell
 isql warehouse
```

**Comment by barnettjacob** [comment]
No, I get a similar error

```
root@379d6d526c49:/# isql -v warehouse
[S1000][unixODBC][FreeTDS][SQL Server]Unable to connect to data source
[ISQL]ERROR: Could not SQLConnect
```

**Comment by jimhester** [comment]
Then the error is definitely in your connection arguments, not in the odbc package. Looking at http://www.sqlstrings.com/SQL-Server-connection-strings.htm and https://www.connectionstrings.com/sql-server/ it looks like the import fields need to be named

- 'User Id' / 'uid'
- 'Password' / 'pwd'
- 'Server'
- 'Database'

Notably you have `host` instead of `Server` in your first example and `UserName` instead of `User ID` or `Uid` in your `odbc.ini`.

**Comment by barnettjacob** [comment]
OK, I'll have a play with that later. Thanks for your help, I'll close the issue. 
Cheers
Jacob
