### ISSUE TITLE
Unable to connect to Redshift on macOS Sierra

### ISSUE THREAD

**Issue by kylelundstedt** [rstats-db/odbc#22]
### Issue Description and Expected Result
Unable to create connection to Amazon Redshift database from Mac running macOS Sierra (10.12.2).  I installed unixodbc via homebrew, and installed the Amazon Redshift ODBC driver per [Amazon's instructions](http://docs.aws.amazon.com/redshift/latest/mgmt/install-odbc-driver-mac.html).  I also have /etc/odbc.ini and /etc/odbcinst.ini configured as per the readme.

### Good News
The good news is that I can connect to Redshift using unixodcb:
```
kyle@KyleDesk:~|⇒  more /etc/odbcinst.ini
[Amazon Redshift]
Driver = /opt/amazon/redshift/lib/libamazonredshiftodbc.dylib
kyle@KyleDesk:~|⇒  more /etc/odbc.ini
[shared_public_read_user]
Driver              = Amazon Redshift
Database            = mortgage
Servername          = xxxxx
UserName            = yyyyy
Password            = zzzzz
Port                = 5439
kyle@KyleDesk:~|⇒  isql -v shared_public_read_user
+---------------------------------------+
| Connected!                            |
```

### Bad News
The bad news is that I can't connect from within R using the same DSN.
```r
library(DBI)
con1 <- dbConnect(odbc::odbc(), dsn = "shared_public_read_user")

> library(DBI)
> con1 <- dbConnect(odbc::odbc(), dsn = "shared_public_read_user")
Error in odbc_connect(connection_string) : 
  nanodbc.cpp:950: IM002: [unixODBC][Driver Manager]Data source name not found, and no default driver specified 
```

Nor can I connect from within R using the same parameters as in the odbcinst.ini file, even if I tweak the connection arguments to match the examples in the README file herein.
```r
con2 <- dbConnect(odbc::odbc(),
                  driver = "Amazon Redshift",
                  database = "mortgage",
                  # servername = "xxxxx",
                  host = "xxxxx",
                  # UserName = "yyyyy",
                  uid = "yyyyy",
                  # password = "zzzzz",
                  pwd = "zzzzz",
                  port = 5439 )

> con2 <- dbConnect(odbc::odbc(),
+                   driver = "Amazon Redshift",
+                   database = "mortgage",
+                   # servername = "xxxxx",
+                   host = "xxxxx",
+                   # UserName = "yyyyy",
+                   uid = "yyyyy",
+                   # password = "zzzzz",
+                   pwd = "zzzzz",
+                   port = 5439 )
Error in odbc_connect(connection_string) : 
  nanodbc.cpp:950: 01000: [unixODBC][Driver Manager]Can't open lib 'Amazon Redshift' : file not found 
```

I'd appreciate any help you could offer!

BTW, thanks for putting together your slides on [Database Best Practices](https://rawgit.com/jimhester/presentations/master/2017_01_13-RStudio_conf-Database_Best_Practices/2017_01_13-RStudio_conf-Database_Best_Practices.html#/).

**Comment by jimhester** [comment]
The amazon instructions you mention seem to be using iODBC, not unixODBC, perhaps that is part of the issue. The [configuration instructions](http://docs.aws.amazon.com/redshift/latest/mgmt/odbc-driver-configure-linux-mac.html) also mention modifying your `LD_LIBRARY_PATH` to ensure the driver libraries are loaded properly. You should ensure this is the case, particularly if you are starting R from somewhere other than the command line (like the RStudio IDE).

Also I would suggest using _exactly_ the same strings in the manual configuration as in your `odbc.ini`, the default strings will likely not work for redshift.

A successful connection with isql should mean that odbc should also work, it is difficult to diagnose the issue without having a redshift instance to test against.

**Comment by kylelundstedt** [comment]
Thanks for the quick reply, @jimhester.  I made progress by substituting in the actual path to the Amazon Redshift driver for the `driver` parameter.  The good news is that the connection succeeds.

However, I get bogus answers when I use the `odbc` functions.  I do have multiple schemas in the mortgage database; per issue #18, is there a workaround to use schema names in the `odbc` functions?

```r
> library(DBI); library(ggplot2)
> con <- dbConnect(
+   odbc::odbc(),
+   driver = "/opt/amazon/redshift/lib/libamazonredshiftodbc.dylib",
+   servername = "mortgage.shared-vault.com", database = "mortgage",
+   UserName = "xxx", Password = "yyy", port = 5439
+ )
> dbListTables(con)
 [1] "c" "c" "d" "d" "g" "g" "l" "l" "l" "p" "a" "a" "c" "d" "e"
[16] "e" "h" "h" "l" "l" "l" "o" "p" "p" "p" "r" "s" "c" "f" "c"
[31] "i" "l" "l" "q" "s" "h" "h" "f" "p" "s" "s" "t" "l" "l" "s"
[46] "v" "i" "i" "i" "i" "i" "m" "m" "m" "m" "m" "z" "c" "l" "c"
[61] "c" "d" "d" "d" "g" "l" "l" "l" "l" "a" "f" "h" "h" "h" "h"
[76] "h" "h" "p" "p"
> dbListTables(con, table_name = "f%")
[1] "f" "f" "f"
> mpg_table <- dbWriteTable(con, "mpg", mpg)
Error in new_result(connection@ptr, statement) : 
  nanodbc.cpp:1587: 42501: [Amazon][Amazon Redshift] (30) Error occurred while trying to execute a query: [SQLState 42501] ERROR:  permission denied for schema cfpb_hmda
```

**Comment by jimhester** [comment]
The single letter table names indicate that a mismatch between the encoding returned by the driver and what unixODBC is expecting.

In the `amazon.redshiftodbc.ini` file, located by default in `/opt/amazon/redshift/lib/amazon.redshiftodbc.ini`, you need to use the following settings

```
DriverManagerEncoding=UTF-8
ODBCInstLib=libodbcinst.so
```

You also may want to set a valid logPath

**Comment by kylelundstedt** [comment]
Hmm.

```
[Driver]
## - Note that this default DriverManagerEncoding of UTF-32 is for iODBC.
# DriverManagerEncoding=UTF-32
DriverManagerEncoding=UTF-8
ErrorMessagesPath=/opt/amazon/redshift/ErrorMessages
LogPath=[LogPath]
SwapFilePath=/tmp

#   iODBC
# ODBCInstLib=libiodbcinst.dylib

ODBCInstLib=libodbcinst.so
```

I then got this output.  😄 Any ideas?
```r
> dbListTables(con)
 [1] "畣楳彰楬歮"                    
 [2] "畣楳彰楬歮慟汬损獵灩"        
...
```

**Comment by jimhester** [comment]
Perhaps try UTF-16? Clearly UTF-8 is not correct...

**Comment by kylelundstedt** [comment]
UTF-16 worked like a charm; awesome!!!  

If I need to read or write to a specific schema, is that possible?

**Comment by jimhester** [comment]
I need to look into schema support a bit more I think, but you can always fall back to writing the SQL by hand if needed and passing it to `dbGetQuery()`.

**Comment by kylelundstedt** [comment]
Sounds good; thanks for all your help!

**Comment by ftoresh** [comment]
I have the same issue with Athena. Any idea?

**Comment by Rey-ND** [comment]
> I have the same issue with Athena. Any idea?
Perhaps try UTF-16 (as jimhester has recommended)

**Comment by ftoresh** [comment]
> I have the same issue with Athena. Any idea?
> Perhaps try UTF-16 (as jimhester has recommended)

Indeed it worked!
