### ISSUE TITLE
Timezone handling

### ISSUE THREAD

**Issue by wurzerj** [rstats-db/odbc#25]
### Issue Description and Expected Result
 `dbGetQuery()` returns incorrect timestamps. When fetching date values from an Oracle database the returned dataset contains the wrong timezone information and the wrong time.

### Database
Database version Oracle 12.01.0020, ODBC version 03.80.0000, Driver Version 11.02.0003, ODBC driver version 03.52

### Reproducible Example
Sys.time() returns "2017-02-08 11:21:46 CET" while the fetched recordset is "2017-02-08 12:21:46 CET". Setting Sys.setenv(TZ="UTC") makes no difference despite all values are shown in UTC (Sys.time() returns 
 "2017-02-08 10:27:22 UTC", the sysdate select returns "2017-02-08 11:27:22 UTC").

```r
> con <- dbConnect(odbc::odbc(), .connection_string="Driver={Oracle in OraClient11g_home1_32bit};Dbq=xxx;Uid=yyy;Pwd=zzz;")
> dbGetQuery(con, "select sessiontimezone from dual UNION ALL select dbtimezone from dual")
  SESSIONTIMEZONE
1          +01:00
2          +01:00
> Sys.time()
[1] "2017-02-08 11:21:46 CET"
> dbGetQuery(con, "select sysdate from dual")[1,1]
[1] "2017-02-08 12:21:46 CET"
dbDisconnect(con)
```

<details>
<summary>Session Info</summary>

```r
> devtools::session_info()
Session info -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.3.1 (2016-06-21)
 system   i386, mingw32               
 ui       Rgui                        
 language (EN)                        
 collate  German_Austria.1252         
 tz       UTC                         
 date     2017-02-08                  

Packages -----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 package    * version date       source        
 assertthat   0.1     2013-12-06 CRAN (R 3.3.1)
 blob         1.0.0   2016-12-29 CRAN (R 3.3.2)
 DBI          0.5-1   2016-09-10 CRAN (R 3.3.1)
 devtools   * 1.12.0  2016-06-24 CRAN (R 3.3.1)
 digest       0.6.11  2017-01-03 CRAN (R 3.3.2)
 memoise      1.0.0   2016-01-29 CRAN (R 3.3.1)
 odbc       * 1.0.1   2017-02-07 CRAN (R 3.3.2)
 Rcpp         0.12.8  2016-11-17 CRAN (R 3.3.2)
 rstudioapi * 0.6     2016-06-27 CRAN (R 3.3.1)
 tibble       1.2     2016-08-26 CRAN (R 3.3.1)
 withr      * 1.0.2   2016-06-20 CRAN (R 3.3.1)
```
</details>

**Comment by jimhester** [comment]
The odbc package expects the session timezone to be in UTC, I think if you [set the session timezone](https://docs.oracle.com/cd/B19306_01/server.102/b14225/ch4datetime.htm#sthref534
) to UTC if will return the values like you would expect. 

```r
Sys.setenv(TZ="CET")
dbClearResult(dbSendQuery(con, "ALTER SESSION SET TIME_ZONE='CET'"))
#> [1] TRUE
dbGetQuery(con, "SELECT CURRENT_TIMESTAMP FROM DUAL")
#>     CURRENT_TIMESTAMP
#> 1 2017-02-08 18:23:45
dbClearResult(dbSendQuery(con, "ALTER SESSION SET TIME_ZONE='UTC'"))
#> [1] TRUE
dbGetQuery(con, "SELECT CURRENT_TIMESTAMP FROM DUAL")
#>     CURRENT_TIMESTAMP
#> 1 2017-02-08 17:23:45
```

**Comment by wurzerj** [comment]
Thanks for the quick answer. Unfortunately this does not seem to solve the problem in my case.

### Example
```r
Sys.setenv(TZ="CET")
con <- dbConnect(odbc::odbc(), .connection_string="Driver={Oracle in OraClient11g_home1_32bit};Dbq=xxx;Uid=yyy;Pwd=zzz;")
dbClearResult(dbSendQuery(con, "ALTER SESSION SET TIME_ZONE='UTC'"))
#>[1] TRUE
dbGetQuery(con, "select 'sessiontimezone' setting, sessiontimezone value from dual UNION ALL select 'dbtimezone', dbtimezone from dual")
#>          SETTING  VALUE
#>1 sessiontimezone    UTC
#>2      dbtimezone +01:00
Sys.time()
#>[1] "2017-02-09 09:36:12 CET"
dbGetQuery(con, "select sysdate from dual")[1,1]
#>[1] "2017-02-09 10:36:12 CET"
```

<details>
<summary>Session Info</summary>

```r
> devtools::session_info()
Session info -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.3.1 (2016-06-21)
 system   i386, mingw32               
 ui       Rgui                        
 language (EN)                        
 collate  German_Austria.1252         
 tz       CET                         
 date     2017-02-09                  

Packages -----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 package    * version date       source        
 assertthat   0.1     2013-12-06 CRAN (R 3.3.1)
 blob         1.0.0   2016-12-29 CRAN (R 3.3.2)
 DBI          0.5-1   2016-09-10 CRAN (R 3.3.1)
 devtools   * 1.12.0  2016-06-24 CRAN (R 3.3.1)
 digest       0.6.11  2017-01-03 CRAN (R 3.3.2)
 memoise      1.0.0   2016-01-29 CRAN (R 3.3.1)
 odbc       * 1.0.1   2017-02-07 CRAN (R 3.3.2)
 Rcpp         0.12.8  2016-11-17 CRAN (R 3.3.2)
 rstudioapi * 0.6     2016-06-27 CRAN (R 3.3.1)
 tibble       1.2     2016-08-26 CRAN (R 3.3.1)
 withr      * 1.0.2   2016-06-20 CRAN (R 3.3.1)
```
</details>

**Comment by jimhester** [comment]
`SYSDATE` by definition is always going to return a timestamp in the system timezone, so is going to be unaffected by the session timezone. You need to use `CURRENT_TIMESTAMP` or `LOCALTIMESTAMP` for a session specific time format.

**Comment by wurzerj** [comment]
Got it, thank you. How would you suggest requesting stored recordsets with proper timezone information from the database? In my case the database timezone is CET. So if I request already stored recordsets the only change I see to get proper values would be building a wrapper around dbGetQuery():
- Setting Sys.setenv(TZ="UTC")
- Requesting the data (now returned "properly", but with UTC timezone)
- Re-classify them from UTC to CET ... not yet thought about it, but probably some lubridate function or string conversion
- Re-setting Sys.setenv(TZ="CET")

As an example:
- I have 2017-02-13 in the database (already stored, database timezone is CET)
- I'd receive 2017-02-13 UTC ... it chould be 2017-02-13 CET
- I'll re-classify it to get 2017-02-13 CET
- Done

Since that sounds terribly inefficient, do you see any other solution for it? Just curious: RODBC handles timezone information differently. Is there a chance to match RODBCs behaviour since propably tons of people would like to migrate from RODBC to your package due to the massive speed increase?

**Comment by jimhester** [comment]
Hmm, I would have expected changing the session timezone to fix how the values are returned, but that doesn't seem to be the case.

Could you try installing this [timezone branch](https://github.com/jimhester/odbc/tree/timezone), then using the timezone parameter to `dbConnect()`.

```r
devtools::install_github("jimhester/odbc@timezone")
library(DBI)
con <- dbConnect(odbc::odbc(), timezone = "CET", .connection_string="Driver={Oracle in OraClient11g_home1_32bit};Dbq=xxx;Uid=yyy;Pwd=zzz;")
```

**Comment by wurzerj** [comment]
I am very sorry, but this does not seem to help. 

### Example
```r
require(RODBC)
require(odbc)

Sys.setenv(TZ="CET")

# Connection string
sCon <- "Driver={Oracle in OraClient11g_home1_32bit};Dbq=xxx;Uid=yyy;Pwd=zzz;"

# SQL request
sSQL <- "select value_date, change_date from tb_series_value where s_id=1 order by change_date desc"

# RODBC connection + request
conOld <- RODBC::odbcDriverConnect(sCon)
dfResOld <- RODBC::sqlQuery(conOld, sSQL, na.strings="NA", stringsAsFactors=FALSE, dec=",")
RODBC::sqlQuery(conOld, "select sessiontimezone from dual UNION ALL select dbtimezone from dual")
  SESSIONTIMEZONE
1          +01:00
2          +01:00

# rodbc connection + request
conNew <- dbConnect(odbc::odbc(), timezone = "CET", .connection_string=sCon)
dfResNew <- dbGetQuery(conNew, sSQL)
dbGetQuery(conNew, "select sessiontimezone from dual UNION ALL select dbtimezone from dual")
  SESSIONTIMEZONE
1          +01:00
2          +01:00

# Output old
head(dfResOld$VALUE_DATE,3)
[1] "2017-02-08 CET" "2017-02-07 CET" "2017-02-06 CET"
head(dfResNew$VALUE_DATE,3)
[1] "2017-02-08 01:00:00 CET" "2017-02-07 01:00:00 CET" "2017-02-06 01:00:00 CET"

head(dfResOld$CHANGE_DATE,3)
[1] "2017-02-08 03:02:06 CET" "2017-02-07 03:06:51 CET" "2017-02-06 03:07:29 CET"
head(dfResNew$CHANGE_DATE,3)
[1] "2017-02-08 04:02:06 CET" "2017-02-07 04:06:51 CET" "2017-02-06 04:07:29 CET"
```

Since I wondered, whether package building worked I checked the following:
- getMethod("dbConnect","OdbcDriver") ... yes, timezone parameter is there
- debug(odbc:::odbc_connect) ... yes, I can also see timezone passed to that function

To to sum up I see exactly the same outputs with timezone set to CET in the timezone branch and the CRAN version of the package.

**Comment by jimhester** [comment]
Ok another attempt I believe this will work properly, could you try the same with the [date](https://github.com/rstats-db/odbc/tree/date) branch in this repository?

```r
devtools::install_github("rstats-db/odbc@date")
```

**Comment by wurzerj** [comment]
Many thanks for your effort. Unfortunately I am not able to install that branch under Windows. It seems that codecvt is causing trouble.

**Errors:**
```r
...
make: [ios.o] Error 127 (ignored)
...
tz.cpp:95:19: fatal error: codecvt: No such file or directory
 #include <codecvt>
                   ^
compilation terminated.
make: *** [tz.o] Error 1
...
```

Are you able to provide a windows binary to test?

<details>
<summary>Session Info</summary>

```r
> devtools::session_info()
Session info ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.3.1 (2016-06-21)
 system   i386, mingw32               
 ui       RStudio (0.99.902)          
 language (EN)                        
 collate  German_Austria.1252         
 tz       Europe/Berlin               
 date     2017-02-15                  

Packages --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 package  * version date       source        
 curl       2.3     2016-11-24 CRAN (R 3.3.2)
 devtools * 1.12.0  2016-06-24 CRAN (R 3.3.1)
 digest     0.6.11  2017-01-03 CRAN (R 3.3.2) 
 httr       1.2.1   2016-07-03 CRAN (R 3.3.1)
 memoise    1.0.0   2016-01-29 CRAN (R 3.3.1)
 R6         2.2.0   2016-10-05 CRAN (R 3.3.2)
 withr      1.0.2   2016-06-20 CRAN (R 3.3.1)`
```
</details>

**Comment by jimhester** [comment]
Ok, new branch that should work on windows without issue.

```r
devtools::install_github("rstats-db/odbc@cctz2")
```

**Comment by jimhester** [comment]
This should now be fixed, if your server is not in UTC, you can specify the server timezone with the `timezone` parameter to the `dbConnect()` method.

**Comment by wurzerj** [comment]
Sorry, did not have the time to test during the last couple days. I can confirm that this is working now. When setting the database timezone in dbConnect() I get proper values, although as you mentioned in UTC. I can then convert these UTC timestamps without any problems to CET. THANKS A LOT!!!

### Output of the sample code posted above:
```r
> head(dfResOld$VALUE_DATE,3)
[1] "2017-02-08 CET" "2017-02-07 CET" "2017-02-06 CET"
> head(dfResNew$VALUE_DATE,3)
[1] "2017-02-07 23:00:00 UTC" "2017-02-06 23:00:00 UTC" "2017-02-05 23:00:00 UTC"
> .POSIXct(head(dfResNew$VALUE_DATE,3))
[1] "2017-02-08 CET" "2017-02-07 CET" "2017-02-06 CET"

> head(dfResOld$CHANGE_DATE,3)
[1] "2017-02-08 03:02:06 CET" "2017-02-07 03:06:51 CET" "2017-02-06 03:07:29 CET"
> head(dfResNew$CHANGE_DATE,3)
[1] "2017-02-08 02:02:06 UTC" "2017-02-07 02:06:51 UTC" "2017-02-06 02:07:29 UTC"
> .POSIXct(head(dfResNew$CHANGE_DATE,3))
[1] "2017-02-08 03:02:06 CET" "2017-02-07 03:06:51 CET" "2017-02-06 03:07:29 CET"
```

**Comment by jimhester** [comment]
Just a note you can use the `format()` method for POSIXct objects to display the times in whatever timezone you would like

```r
x <- .POSIXct(Sys.time(), tz = "UTC")
format(x)
#> [1] "2017-02-21 13:37:29"
format(x, tz = "EST")
#> [1] "2017-02-21 08:37:29"
format(x, tz = "CET")
#> [1] "2017-02-21 14:37:29"
```

**Comment by wurzerj** [comment]
I know, .POSIXct made no sense in that example, but in my script it does (I need the POSIXct and not a character). Anyway, thanks!

**Comment by r2evans** [comment]
@jimhester, I can create a new issue for this, but this is directly related to this and #54.

What are your thoughts on supporting timestamp types that include timezone/offset information? Postgres has `TIMESTAMPTZ` and MSSQL has `DATETIMEOFFSET`.

In more and more of my work, I find I cannot trust the other client apps to correctly handle offset on their own, so they are just sending the stamp with offset part of the data. Though "education" would be an alternative, I've tried that and can now say authoritatively that trusting the user (and some other programmers) is still wrong. ("Never trust the user" in testing is a mantra of mine.)

As I look through the code, I see the `datetime` references ... I know it's not "simple", but is there a way forward by duplicating these structs and extending for `datetimeoffset` (and similar formats)? I recognize not every DBMS supports it, so perhaps those drivers could just duplicate or "not support" it. (I guess one question is this: is the lack of "datetime with offset" a limitation of `odbc::`, `DBI::`, or ODBC itself?)

**Comment by mkirzon** [comment]
@r2evans I completely agree with your assessment. Education is the alternative, but I keep finding that trusting end users with timezone handling fails. 
I'm coming back to the challenge that odbc doesn't allow leveraging known timezone specifications on the database side. Timezones can be configured in 1) server wide (#332 ), or 2) within timezone aware columns. 

@jimhester It looks like the RPostgreSQL library correctly handles timezones. Is there anyway to bring in the functionality to odbc?
