### ISSUE TITLE
Unknown field type -11 with uniqueidentifier and SQL Server

### ISSUE THREAD

**Issue by dmenne** [rstats-db/odbc#26]
### Issue Description and Expected Result
dbGetQuery reports "Unknown field type (-11) in column..." with uniqueidentifier

It's a warning only, results look ok (character)

### Database
SQL Server 13.0.1722 under Windows 64

odbc 1.0.1 from CRAN

**Comment by dmenne** [comment]
This example works with RODB without warning. 

```
library(odbc)
con = dbConnect(odbc::odbc(), .connection_string =
"DRIVER={SQL Server Native Client 11.0};SERVER=DIETERPC;Trusted_Connection=yes")
dbSendQuery(con, "DROP DATABASE test")
dbSendQuery(con, "CREATE DATABASE test")
dbSendQuery(con, "CREATE TABLE test.dbo.mytab (u uniqueidentifier NOT NULL)")
dbSendQuery(con, "INSERT into test.dbo.mytab Values (NEWID())")
dbGetQuery(con, "SELECT * from test.dbo.mytab")


#In result_fetch(res@ptr, n, ...) : Unknown field type (-11) in column u

```

**Comment by dmenne** [comment]
I agree that it works as intended (character data), but it's ugly that I have to wrap every query with `suppressWarnings`, so I went back to RODBC. uniqueidentifier fields  are everywhere in SQL Server. Maybe some global option would be nice to suppress "unknown field type warnings"?

**Comment by jimhester** [comment]
These no longer signal warnings, instead they signal custom conditions which can be caught if desired.

**Comment by dmenne** [comment]
Tested. Ok. Thanks, Jim.
