### ISSUE TITLE
`dbWriteTable()` needs a fallback if transactions are not supported by a driver

### ISSUE THREAD

**Issue by jimhester** [rstats-db/odbc#32]
### Issue Description and Expected Result
`dbWriteTable()` needs a fallback if transactions are not supported by a driver. Currently the code assumes it can use transactions, but not all ODBC drivers support them. 

### Database
Magnitude Spark Db / Driver does not support transactions.

**Comment by rachelgarza** [comment]
This also affects the MongoDB driver.

**Comment by jimhester** [comment]
Also the Impala Driver

**Comment by jimhester** [comment]
This should now be fixed.
