### ISSUE TITLE
Error message needs newlines?

### ISSUE THREAD

**Issue by hadley** [rstats-db/odbc#44]
```
Error in odbc_connect(connection_string, timezone = timezone) : 
  nanodbc.cpp:950: 01000: [unixODBC][Driver Manager]Can't open lib 'SQLite Driver' : file not found 
```

Ideally would be

```
Error: nanodbc.cpp:950: 01000: [unixODBC][Driver Manager]
Can't open lib 'SQLite Driver' : file not found 
```

**Comment by jimhester** [comment]
`[unixODBC][Driver Manager]Can't open lib 'SQLite Driver' : file not found` is the raw string returned directly from the Driver / Driver Manager and is not standardized. So the only way we can add a newline would be to assume two bracketed expressions and add a newline after the second, which I think could work..

**Comment by jimhester** [comment]
The call requires changes to Rcpp https://github.com/RcppCore/Rcpp/issues/664, or to catch the condition objects and remove the call.
