### ISSUE TITLE
Compiling odbc pkg fails with "no matching function call to Rcpp::exception::exception"

### ISSUE THREAD

**Issue by aryoda** [rstats-db/odbc#59]
I am trying to compile the the current version of the `odbc` package (commit f311ac2bfefac001f99c4f2079c1fb07a65935c1) on Ubuntu 14.04 as well as on Windows 7 using RStudio 1.0.x.

The build process fails with

* odbc_connection.h:26:44: error: no matching function for call to 'Rcpp::exception::exception(const char*, int)'
*  odbc_result.h:26:34: error: no matching function for call to 'Rcpp::exception::exception(const char [1], bool)'

I am using R 3.2.2 64 Bit on Windows and Ubuntu.
Rcpp is installed via CRAN (version Rcpp_0.12.10).

It looks like the Rcpp constructors that `odbc` calls now have changed but I am compiling against and "old" `Rcpp` version (even though the most recent one available on CRAN), e. g.

*odbc_connection.h:*
```
   try {
      c_ = std::make_shared<nanodbc::connection>(connection_string);
    } catch (nanodbc::database_error e) {
      throw Rcpp::exception(e.what(), FALSE);
    }

```
Can you reproduce this behaviour? Any recommendation how to build the package (e. g. installing `Rcpp` from github)?

THX!

**Build log details:**

> In file included from odbc_types.h:5:0,
>                  from connection.cpp:4:
> odbc_connection.h: In constructor 'odbc::odbc_connection::odbc_connection(std::string, std::string, std::string)':
> odbc_connection.h:26:44: error: no matching function for call to 'Rcpp::exception::exception(const char*, int)'
>        throw Rcpp::exception(e.what(), FALSE);
>                                             ^
> odbc_connection.h:26:44: note: candidates are:
> In file included from C:/Users/Public/inst/R-3.3.2/library/Rcpp/include/RcppCommon.h:122:0,
>                  from C:/Users/Public/inst/R-3.3.2/library/Rcpp/include/Rcpp.h:27,
>                  from connection.cpp:1:
> C:/Users/Public/inst/R-3.3.2/library/Rcpp/include/Rcpp/exceptions.h:34:9: note: Rcpp::exception::exception(const char*, const char*, int)
>          exception(const char* message_, const char* file, int line) : message(message_) {
>          ^
> C:/Users/Public/inst/R-3.3.2/library/Rcpp/include/Rcpp/exceptions.h:34:9: note:   candidate expects 3 arguments, 2 provided
> C:/Users/Public/inst/R-3.3.2/library/Rcpp/include/Rcpp/exceptions.h:31:18: note: Rcpp::exception::exception(const char*)
>          explicit exception(const char* message_) : message(message_) { // #nocov start
>                   ^
> C:/Users/Public/inst/R-3.3.2/library/Rcpp/include/Rcpp/exceptions.h:31:18: note:   candidate expects 1 argument, 2 provided
> C:/Users/Public/inst/R-3.3.2/library/Rcpp/include/Rcpp/exceptions.h:29:11: note: Rcpp::exception::exception(const Rcpp::exception&)
>      class exception : public std::exception {
>            ^
> C:/Users/Public/inst/R-3.3.2/library/Rcpp/include/Rcpp/exceptions.h:29:11: note:   candidate expects 1 argument, 2 provided
> In file included from odbc_types.h:6:0,
>                  from connection.cpp:4:
> odbc_result.h: In constructor 'odbc::odbc_error::odbc_error(nanodbc::database_error, const string&)':
> odbc_result.h:26:34: error: no matching function for call to 'Rcpp::exception::exception(const char [1], bool)'
>        : Rcpp::exception("", false) {
>                                   ^
> odbc_result.h:26:34: note: candidates are:
> In file included from C:/Users/Public/inst/R-3.3.2/library/Rcpp/include/RcppCommon.h:122:0,
>                  from C:/Users/Public/inst/R-3.3.2/library/Rcpp/include/Rcpp.h:27,
>                  from connection.cpp:1:
> C:/Users/Public/inst/R-3.3.2/library/Rcpp/include/Rcpp/exceptions.h:34:9: note: Rcpp::exception::exception(const char*, const char*, int)
>          exception(const char* message_, const char* file, int line) : message(message_) {
>          ^
> C:/Users/Public/inst/R-3.3.2/library/Rcpp/include/Rcpp/exceptions.h:34:9: note:   candidate expects 3 arguments, 2 provided
> C:/Users/Public/inst/R-3.3.2/library/Rcpp/include/Rcpp/exceptions.h:31:18: note: Rcpp::exception::exception(const char*)
>          explicit exception(const char* message_) : message(message_) { // #nocov start
>                   ^
> C:/Users/Public/inst/R-3.3.2/library/Rcpp/include/Rcpp/exceptions.h:31:18: note:   candidate expects 1 argument, 2 provided
> C:/Users/Public/inst/R-3.3.2/library/Rcpp/include/Rcpp/exceptions.h:29:11: note: Rcpp::exception::exception(const Rcpp::exception&)
>      class exception : public std::exception {
>            ^
> C:/Users/Public/inst/R-3.3.2/library/Rcpp/include/Rcpp/exceptions.h:29:11: note:   candidate expects 1 argument, 2 provided
> make: *** [connection.o] Error 1
>

**Comment by jimhester** [comment]
install the odbc package with `devtools::install_github("rstats-db/odbc")`, it will install the devel version of Rcpp needed automatically. You can also install locally with `devtools::install()` and it will do the same thing See (https://github.com/rstats-db/odbc/blob/master/DESCRIPTION#L43) and the vignette on remote dependencies https://github.com/hadley/devtools/blob/master/vignettes/dependencies.Rmd

**Comment by aryoda** [comment]
Great, I can build now!

Using `devtools::install()` in RStudio within the `odbc` project containing the source code pulled via git solved my problem.

THX for your good explanation of remote dependencies (didn't know this until today :-)
