### ISSUE TITLE
Errors while compiling in Windows 7 enterprise

### ISSUE THREAD

**Issue by karpatit** [rstats-db/odbc#62]
### Issue Description and Expected Result
After downloading I opened the project on RStudio and tried to build the package. After a while it returned with the following two errors:

**src/odbc_connection.h**
Line 23 no matching function for call to 'Rcpp::exception::exception(const char*, int)'

**src/odbc_result.h**
Line 25 no matching function for call to 'Rcpp::exception::exception(const cha [1], bool)'

### Database
Database is "Microsoft SQL Server 12.0.5000.0"

**Comment by jimhester** [comment]
install the package with `devtools::install()`, it will install the appropriate version of Rcpp for you.
