### ISSUE TITLE
Cannot set transaction isolation level in SQL Server

### ISSUE THREAD

**Issue by dgrtwo** [rstats-db/odbc#63]
### Issue Description and Expected Result

When I execute a `SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED` query on a SQL Server database, it doesn't change the [isolation level](https://docs.microsoft.com/en-us/sql/odbc/reference/develop-app/transaction-isolation-levels). That can be determined with a `SELECT transaction_isolation_level FROM sys.dm_exec_sessions where session_id = @@SPID` query. Setting this transaction level is necessary for production databases so that queries from R don't lock out other queries.

### Database

Microsoft SQL Server, both 2012 (see below) and 2016.

### Reproducible Example

Here's an example on the sample AdventureWorks2012 database (though I get the same problem on our own database, running SQL Server 2016).

``` r
library(DBI)
con <- dbConnect(odbc::odbc(),
                 driver = "libtdsodbc.so",
                 database = "AdventureWorks2012",
                 uid = "sqlfamily",
                 pwd = "sqlf@m1ly",
                 Server = "mhknbn2kdz.database.windows.net",
                 port = 1433)

# First check the transaction level
s <- "SELECT transaction_isolation_level FROM sys.dm_exec_sessions where session_id = @@SPID"
DBI::dbGetQuery(con, s)
#>   transaction_isolation_level
#> 1                           2

# This should change it to 1
q <- "SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED"
set_result <- DBI::dbExecute(con, q)

# But it does not:
s <- "SELECT transaction_isolation_level FROM sys.dm_exec_sessions where session_id = @@SPID"
DBI::dbGetQuery(con, s)
#>   transaction_isolation_level
#> 1                           2
```

<details>
``` r
devtools::session_info()
#> Session info -------------------------------------------------------------
#>  setting  value                       
#>  version  R version 3.4.0 (2017-04-21)
#>  system   x86_64, darwin15.6.0        
#>  ui       X11                         
#>  language (EN)                        
#>  collate  en_US.UTF-8                 
#>  tz       America/New_York            
#>  date     2017-05-30
#> Packages -----------------------------------------------------------------
#>  package   * version date       source        
#>  backports   1.1.0   2017-05-22 CRAN (R 3.4.0)
#>  base      * 3.4.0   2017-04-21 local         
#>  compiler    3.4.0   2017-04-21 local         
#>  datasets  * 3.4.0   2017-04-21 local         
#>  devtools    1.13.1  2017-05-13 CRAN (R 3.4.0)
#>  digest      0.6.12  2017-01-27 CRAN (R 3.4.0)
#>  evaluate    0.10    2016-10-11 CRAN (R 3.4.0)
#>  graphics  * 3.4.0   2017-04-21 local         
#>  grDevices * 3.4.0   2017-04-21 local         
#>  htmltools   0.3.6   2017-04-28 cran (@0.3.6) 
#>  knitr       1.16    2017-05-18 CRAN (R 3.4.0)
#>  magrittr    1.5     2014-11-22 CRAN (R 3.4.0)
#>  memoise     1.1.0   2017-04-21 CRAN (R 3.4.0)
#>  methods   * 3.4.0   2017-04-21 local         
#>  Rcpp        0.12.11 2017-05-22 CRAN (R 3.4.0)
#>  rmarkdown   1.5     2017-04-26 CRAN (R 3.4.0)
#>  rprojroot   1.2     2017-01-16 CRAN (R 3.4.0)
#>  stats     * 3.4.0   2017-04-21 local         
#>  stringi     1.1.5   2017-04-07 CRAN (R 3.4.0)
#>  stringr     1.2.0   2017-02-18 CRAN (R 3.4.0)
#>  tools       3.4.0   2017-04-21 local         
#>  utils     * 3.4.0   2017-04-21 local         
#>  withr       1.0.2   2016-06-20 CRAN (R 3.4.0)
#>  yaml        2.1.14  2016-11-12 cran (@2.1.14)
```
</details>

**Comment by NickLarsen** [comment]
The root cause of this is in the nanodbc project.  Once a fix is found there, this project will need to update it's version of nanodbc.

https://github.com/lexicalunit/nanodbc/issues/276

**Comment by jimhester** [comment]
Sorry I haven't had a chance to look at this sooner, thank you @NickLarsen for looking into it. I am not sure why setting the transaction level is not persisting for the entire duration of the connection. However it does seem to work if you set the transaction level before each statement.

```r
dbGetQuery(con, "SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;SELECT transaction_isolation_level FROM sys.dm_exec_sessions where session_id = @@SPID")
#>   transaction_isolation_level
#> 1                           1
```

**Comment by jimhester** [comment]
I added a function `odbcSetTransactionIsolationLevel` to allow users to set the transaction isolation level per connection (using SQLSetConnectAttr)`.

```r
# establish connection as above
odbcSetTransactionIsolationLevel(con, "read uncommitted")
s <- "SELECT transaction_isolation_level FROM sys.dm_exec_sessions where session_id = @@SPID"
DBI::dbGetQuery(con, s)

#>   transaction_isolation_level
#> 1                           1
```

**Comment by dgrtwo** [comment]
Fantastic, works like a charm!

**Comment by juliasilge** [comment]
When I install from commit 2d1bbe88d7ee0b55c1d20677b0a6dcdadb8d1366, the function `odbcSetTransactionIsolationLevel` works as expected, but for commits afterward, the transaction level is not persisting again.

``` r
odbcSetTransactionIsolationLevel(con, "read uncommitted")
s <- "SELECT transaction_isolation_level FROM sys.dm_exec_sessions where session_id = @@SPID"
DBI::dbGetQuery(con, s)
#>   transaction_isolation_level
#> 1                           2
```

Do you think something has changed since that commit that broke this?

**Comment by jimhester** [comment]
Sorry Julia, I changed the type of the argument to avoid a compiler warning, and it inadvertently broke the function. Should be fixed by e77b11a81dfad04.

**Comment by mloskot** [comment]
https://github.com/rstats-db/odbc/issues/63#issuecomment-308191578
>The root cause of this is in the nanodbc project. 

Is there?
Since nanodbc is a very thin wrapper and I think it does not interfere with the SQL command mode.

It has been said in the bug report
> query method shown above is preferable, but I have not been able to debug why that's not working

So, I'm not sure it is entirely correct to judge the root of the problem is in nanodbc.

**Comment by NickLarsen** [comment]
@mloskot that's fair.  We previously were using another R package that uses java under the hood to connect to sql server.  With that package we were able to make the requests shown above and achieve the desired result.  Our decision to switch to this odbc package is almost entirely because of the massive headache in getting that other package installed compared to the relatively easy install for this package.

I said the root cause was in the nanodbc because when using that alone I was able to reproduce the issue shown above without any of the R code from this package.  I was not completely familiar with the goals of the nanodbc project when I said that, and nanodbc did have enough functionality to support resolving this issue here without modification.

**Comment by jimhester** [comment]
We do not see the same behavior with `RODBC`, which also uses ODBC but does not use nanodbc, so this does seem to be a difference related to the nanodbc library.

```r
library(RODBC)
con = odbcConnection("SQLServer")

q <- "SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED"
set_result <- sqlQuery(con, q)

s <- "SELECT transaction_isolation_level FROM sys.dm_exec_sessions where session_id = @@SPID"
sqlQuery(con, s)
#>   transaction_isolation_level
#> 1                           1

**Comment by mloskot** [comment]
@jimhester Raw ODBC API is what I was going to try out. So, thanks for doing it.
I have reopened the nanodbc issue https://github.com/lexicalunit/nanodbc/issues/276 It is worth to find out what is the difference.
