### ISSUE TITLE
Provide fallback implementation to use when parameter binding fails

### ISSUE THREAD

**Issue by jimhester** [rstats-db/odbc#70]
Some databases / drivers have issues with the way nanodbc does parameter binding for inserting data. https://github.com/rstats-db/odbc/issues/66, https://github.com/rstats-db/odbc/issues/30. To work around the issue we can provide a fallback `odbcWriteTableSQL()` function that writes the values as text rather than binding a column. This requires escaping the data specially for things like Dates, datetimes and missing data.

**Comment by jimhester** [comment]
We are providing a VARCHAR fallback now, which seems to avoid the issue without having to do the proposal here.

**Comment by detule** [comment]
@jimhester would you be interested in a back-port of https://github.com/nanodbc/nanodbc/commit/e99606bc8d01257c7c1316dd06f3a9c30e0a71fd (happy to do it)?
