### ISSUE TITLE
Fetching GUID data type columns gives a warning

### ISSUE THREAD

**Issue by huftis** [rstats-db/odbc#73]
### Issue Description and Expected Result
If an SQL Server data base contains a GUID field, `dbReadTable(db, "tablename")` (and similar commands) issue warnings like this:

    Warning message:
    In result_fetch(res@ptr, n, ...) : Unknown field type (-11) in column guid

However, the field is read as a string, and works perfectly fine.

### Database
```r
> dbGetInfo(db)
$dbms.name
[1] "Microsoft SQL Server"

$db.version
[1] "11.00.6020"
```

### Additional information
There is some information about the data type at https://docs.microsoft.com/en-us/sql/t-sql/data-types/uniqueidentifier-transact-sql
And more information on the various ODBC SQL data types at https://docs.microsoft.com/en-us/sql/odbc/reference/appendixes/appendix-d-data-types. According to that document ,the GUID data type has the ODBC SQL data type name `SQL_GUID` (numeric identifier: `-11`).

Treating the value as a string should be OK, so the only thing that needs to be done to ‘fix’ this bug is to make the warning go away. :)

<details>
<summary>Session Info</summary>

```r
> devtools::session_info()
Session info ----------------------------------------------------------------------------------------------------------------------
 setting  value                        
 version  R version 3.4.0 (2017-04-21) 
 system   x86_64, mingw32              
 ui       RStudio (1.0.143)            
 language (EN)                         
 collate  Norwegian-Nynorsk_Norway.1252
 tz       Europe/Berlin                
 date     2017-06-16                   

Packages --------------------------------------------------------------------------------------------------------------------------
 package   * version date       source        
 base      * 3.4.0   2017-04-21 local         
 blob        1.0.0   2016-12-29 CRAN (R 3.4.0)
 compiler    3.4.0   2017-04-21 local         
 datasets  * 3.4.0   2017-04-21 local         
 DBI       * 0.6-1   2017-04-01 CRAN (R 3.4.0)
 devtools    1.13.2  2017-06-02 CRAN (R 3.4.0)
 digest      0.6.12  2017-01-27 CRAN (R 3.4.0)
 graphics  * 3.4.0   2017-04-21 local         
 grDevices * 3.4.0   2017-04-21 local         
 memoise     1.1.0   2017-04-21 CRAN (R 3.4.0)
 methods   * 3.4.0   2017-04-21 local         
 odbc      * 1.0.1   2017-02-07 CRAN (R 3.4.0)
 Rcpp        0.12.11 2017-05-22 CRAN (R 3.4.0)
 rlang       0.1.1   2017-05-18 CRAN (R 3.4.0)
 stats     * 3.4.0   2017-04-21 local         
 tibble      1.3.3   2017-05-28 CRAN (R 3.4.0)
 tools       3.4.0   2017-04-21 local         
 utils     * 3.4.0   2017-04-21 local         
 withr       1.0.2   2016-06-20 CRAN (R 3.4.0)
```
</details>

**Comment by jimhester** [comment]
This was changed from a warning to signaling a custom condition in the devel version of odbc, so it would now be silent.
