### ISSUE TITLE
dbWriteTable(temporary=TRUE) error with SQL

### ISSUE THREAD

**Issue by dfalty** [rstats-db/odbc#74]
### Issue Description and Expected Result
dbWriteTable(temporary=TRUE) error with SQL

Error in new_result(connection@ptr, statement) : nanodbc/nanodbc.cpp:1344: HY000: Unknown object type 'TEMPORARY' used in a CREATE, DROP, or ALTER statement., Statement(s) could not be prepared.,
10.stop(structure(list(message = "nanodbc/nanodbc.cpp:1344: HY000: Unknown object type 'TEMPORARY' used in a CREATE, DROP, or ALTER statement., Statement(s) could not be prepared., ", call = new_result(connection@ptr, statement), cppstack = NULL), .Names = c("message", "call", "cppstack"), class = c("nanodbc::database_error", "C++Error", "error", "condition")))
9.new_result(connection@ptr, statement)
8.OdbcResult(connection = conn, statement = statement)
7.dbSendStatement(conn, statement, ...)
6.dbSendStatement(conn, statement, ...)
5.dbExecute(conn, sql)
4.dbExecute(conn, sql)
3..local(conn, name, value, ...)
2.dbWriteTable(odbcSQLSeverCon, "tempmtcars", mtcars, temporary = TRUE)
1.dbWriteTable(odbcSQLSeverCon, "tempmtcars", mtcars, temporary = TRUE)

### Database
SQL Server Express 12.00.4422.0.v1 

### Reproducible Example

Example:
```r
library(odbc)
library(DBI)
odbcSQLSeverCon <- dbConnect(odbc(),Driver = "SQLServer",Server = "<server>",Database = "<database>",UID = "<uid>", PWD = "<PWD>",Port = <port>)
dbWriteTable(odbcSQLSeverCon, "tempmtcars", mtcars, temporary = TRUE)
```

<details>
<summary>Session Info</summary>

```r
> devtools::session_info()
Session info ------------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.3.2 (2016-10-31)
 system   x86_64, linux-gnu           
 ui       RStudio (1.0.143)           
 language (EN)                        
 collate  en_US.UTF-8                 
 tz       America/New_York            
 date     2017-06-19                  

Packages ----------------------------------------------------------------------------------------------------
 package   * version    date       source                         
 base      * 3.3.2      2016-12-15 local                          
 bit         1.1-12     2014-04-09 cran (@1.1-12)                 
 bit64       0.9-7      2017-05-08 cran (@0.9-7)                  
 blob        1.1.0      2017-06-19 Github (hadley/blob@9dd54d9)   
 datasets  * 3.3.2      2016-12-15 local                          
 DBI       * 0.7        2017-06-18 cran (@0.7)                    
 devtools    1.13.1     2017-05-13 CRAN (R 3.3.2)                 
 digest      0.6.12     2017-01-27 CRAN (R 3.3.2)                 
 graphics  * 3.3.2      2016-12-15 local                          
 grDevices * 3.3.2      2016-12-15 local                          
 hms         0.3        2016-11-22 cran (@0.3)                    
 knitr       1.16       2017-05-18 CRAN (R 3.3.2)                 
 memoise     1.1.0      2017-04-21 CRAN (R 3.3.2)                 
 methods   * 3.3.2      2016-12-15 local                          
 odbc      * 1.0.1.9000 2017-06-19 Github (rstats-db/odbc@6580a3e)
 Rcpp        0.12.11    2017-05-22 CRAN (R 3.3.2)                 
 rlang       0.1.1      2017-05-18 cran (@0.1.1)                  
 stats     * 3.3.2      2016-12-15 local                          
 tibble      1.3.3      2017-05-28 cran (@1.3.3)                  
 tools       3.3.2      2016-12-15 local                          
 utils     * 3.3.2      2016-12-15 local                          
 withr       1.0.2      2016-06-20 CRAN (R 3.3.2)
```
</details>

**Comment by nwstephens** [comment]
This works:
copy_to(my_table, "##my_table", TEMPORARY = FALSE)

Test this:
dbWriteTable(odbcSQLSeverCon, "##tempmtcars", mtcars, temporary = FALSE)

Consider writing a method for dbplyr or odbc for sql server specifically.

**Comment by dfalty** [comment]
dbWriteTable(odbcSQLSeverCon, "##tempmtcars", mtcars, temporary = FALSE) 
Works for me. I was about to close this after verifying dbGetQuery() works fine on the temporary table but I did notice that dbExistsTable() returns FALSE even though the temporary table exists. What's the expected behavior here?

dbExistsTable(odbcSQLSeverCon, "##tempmtcars")

**Comment by jimhester** [comment]
For SQL Server the tables are listed only in the `tempdb` catalog.

There was a bug where `dbExistsTable()` did not pass on `...` to `dbListTables()`; fixed by f1aa7de. 

So you can now do the following to find the temporary tables on SQL Server.

```r
library(DBI);con <- dbConnect(odbc::odbc(), "SimbaSQLServer", UID = 'FOO', PWD = 'BAR')
dbWriteTable(con, "##mtcars", mtcars)
dbExistsTable(con, "##mtcars", catalog_name = "tempdb")
#> [1] TRUE
```
 
Should note this does _not_ work with the freetds driver, which doesn't seem to handle the catalogs properly in this case. I am not sure if the windows native driver does this correctly, but I believe it should.

**Comment by dfalty** [comment]
Yup, that did it. Thanks for the info! Closing issue

**Comment by ldfreight** [comment]
using odbc '1.1.5'

`odbc::dbWriteTable(con, name = "#mytable", value = df)`

returns

> nanodbc/nanodbc.cpp:1587: 42S02: [Microsoft][ODBC SQL Server Driver][SQL Server]Invalid object name '#mytable'

**Comment by mimaque** [comment]
@jimhester thanks for pointing out that FreeTDS doesn't handle the catalogs properly... Any ideas then on how to dbWriteTable to an SQL Server using the FreeTDS? Or should I download the specific SQL Server drivers for my Ubuntu machine as a workaround?

**Comment by jimhester** [comment]
I would try using the microsoft SQL Server drivers for ubuntu, although I have not used them myself I imagine they have better support.
