### ISSUE TITLE
dbWriteTable() fails for Salesforce

### ISSUE THREAD

**Issue by dfalty** [rstats-db/odbc#75]
### Issue Description and Expected Result
dbWriteTable() fails for Salesforce
Error in new_result(connection@ptr, statement) : nanodbc/nanodbc.cpp:1344: HY000: [RStudio][Salesforce] (120) SOQL_FIRST mode prepare failure: SOQL error: [RStudio][SQLEngine] (31480) syntax error near 'CREATE<<< ??? >>> TABLE "mtcars" ( "row_names" VARCHAR(255), "mpg" DOUBLE, "cyl" DOUBLE, "disp" DOUBLE, "hp" DOUBLE, "drat" DOUBLE, "wt" DOUBLE, "qsec" DOUBLE, "vs" DOUBLE, "am" DOUBLE, "gear" DOUBLE, "carb" DOUBLE ) '. SQL error: [RStudio][SQLEngine] (31781) Create table statements are not supported.
10.stop(structure(list(message = "nanodbc/nanodbc.cpp:1344: HY000: [RStudio][Salesforce] (120) SOQL_FIRST mode prepare failure:\nSOQL error: [RStudio][SQLEngine] (31480) syntax error near 'CREATE<<< ??? >>> TABLE \"mtcars\" (\n \"row_names\" VARCHAR(255),\n \"mpg\" DOUBLE,\n \"cyl\" DOUBLE,\n \"disp\" DOUBLE,\n \"hp\" DOUBLE,\n \"drat\" DOUBLE,\n \"wt\" DOUBLE,\n \"qsec\" DOUBLE,\n \"vs\" DOUBLE,\n \"am\" DOUBLE,\n \"gear\" DOUBLE,\n \"carb\" DOUBLE\n)\n'.\nSQL error: [RStudio][SQLEngine] (31781) Create table statements are not supported. ", call = new_result(connection@ptr, statement), cppstack = NULL), .Names = c("message", "call", "cppstack"), class = c("nanodbc::database_error", "C++Error", "error", "condition")))
9.new_result(connection@ptr, statement)
8.OdbcResult(connection = conn, statement = statement)
7.dbSendStatement(conn, statement, ...)
6.dbSendStatement(conn, statement, ...)
5.dbExecute(conn, sql)
4.dbExecute(conn, sql)
3..local(conn, name, value, ...)
2.dbWriteTable(odbcSFCon, "mtcars", mtcars)
1.dbWriteTable(odbcSFCon, "mtcars", mtcars)

### Database
Salesforce

### Reproducible Example
Example:
```r
library(odbc)
library(DBI)
odbcSFCon <- dbConnect(odbc(),Driver = "Salesforce",PWD = "<PWD>",UID = "<UID>",SecurityToken='<SecurityToken>')
dbWriteTable(odbcSFCon, "mtcars", mtcars)
```

<details>
<summary>Session Info</summary>

```r
> devtools::session_info()
Session info ------------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.3.2 (2016-10-31)
 system   x86_64, linux-gnu           
 ui       RStudio (1.0.143)           
 language (EN)                        
 collate  en_US.UTF-8                 
 tz       America/New_York            
 date     2017-06-19                  

Packages ----------------------------------------------------------------------------------------------------
 package   * version    date       source                         
 base      * 3.3.2      2016-12-15 local                          
 bit         1.1-12     2014-04-09 cran (@1.1-12)                 
 bit64       0.9-7      2017-05-08 cran (@0.9-7)                  
 blob        1.1.0      2017-06-19 Github (hadley/blob@9dd54d9)   
 datasets  * 3.3.2      2016-12-15 local                          
 DBI       * 0.7        2017-06-18 cran (@0.7)                    
 devtools    1.13.1     2017-05-13 CRAN (R 3.3.2)                 
 digest      0.6.12     2017-01-27 CRAN (R 3.3.2)                 
 graphics  * 3.3.2      2016-12-15 local                          
 grDevices * 3.3.2      2016-12-15 local                          
 hms         0.3        2016-11-22 cran (@0.3)                    
 knitr       1.16       2017-05-18 CRAN (R 3.3.2)                 
 memoise     1.1.0      2017-04-21 CRAN (R 3.3.2)                 
 methods   * 3.3.2      2016-12-15 local                          
 odbc      * 1.0.1.9000 2017-06-19 Github (rstats-db/odbc@6580a3e)
 Rcpp        0.12.11    2017-05-22 CRAN (R 3.3.2)                 
 rlang       0.1.1      2017-05-18 cran (@0.1.1)                  
 stats     * 3.3.2      2016-12-15 local                          
 tibble      1.3.3      2017-05-28 cran (@1.3.3)                  
 tools       3.3.2      2016-12-15 local                          
 utils     * 3.3.2      2016-12-15 local                          
 withr       1.0.2      2016-06-20 CRAN (R 3.3.2)
```
</details>

**Comment by jimhester** [comment]
The relevant error message is `SQL error: [RStudio][SQLEngine] (31781) Create table statements are not supported.`, which indicates that create table statements are not supported by the driver. So there are no changes possible in the **odbc** package.

If table creation is something we are looking for with the Salesforce driver we would need to talk to Magnitude about adding the functionality. However there are presumably reasons it is not supported currently, so this may not be possible.

**Comment by nwstephens** [comment]
Simba says that this driver does not support Data Definition Language (DDL):

Created By: Anastasiya Gerasimova (7/13/2017 2:12 PM)Hello Nathan, The driver does not support DDL. Is that is answering your questions may we close this ticket? Thank you, Anastasiya
