### ISSUE TITLE
return datetime added 8hours

### ISSUE THREAD

**Issue by feng5** [rstats-db/odbc#8]
`con %>% dbSendQuery("select ordernum,addtime,to_char(addtime, 'yyyy-mm-dd hh24:mi:ss') as addtime2 from TEST.V_HPME_TBL_WP_ORDER where ordernum='399937536016100321515559'") %>% dbFetch()`
what i got is `addtime = addtime2 + lubridate::hours(8)`, is there a way to handle timezone?

**Comment by jimhester** [comment]
What type of database are you querying and what is your local timezone, and what is the database timezone?

**Comment by feng5** [comment]
Oracle with timezone `+00:00`, and local timezone is `+08:00`

**Comment by jimhester** [comment]
Could you try running the following, modifying the connection string as needed.

``` r
library(DBI)
library(odbconnect)
con <- dbConnect(odbconnect::odbconnect(), dsn = "PostgreSQL")
dbGetQuery(con, "SELECT to_char(TIMESTAMP '1997-01-31 09:26:50.12', 'yyyy-mm-dd- hh24:mi:ss') as a, TIMESTAMP '1997-01-31 09:26:50.12' as b")
#>                      a                   b
#> 1 1997-01-31- 09:26:50 1997-01-31 04:26:50
```

You can see above the displayed time is offset by my timezone (-500), as R displays `POSIXct` objects in the local timezone. You can display it in UTC with `format(x, tz = "UTC")`.

**Comment by feng5** [comment]
```
> dbGetQuery(con, "SELECT to_char(sysdate, 'yyyy-mm-dd- hh24:mi:ss') as a,sysdate as b from dual")
                     A                   B
1 2016-11-10- 13:12:21 2016-11-10 21:12:21
```
my local windows time is `2016-11-10- 13:12:25`
