### ISSUE TITLE
Problems setting up DSNs and connecting with Oracle

### ISSUE THREAD

**Issue by joranE** [rstats-db/odbc#85]
### Issue Description and Expected Result
I'm unable to connect to my Oracle db on a Mac. At the moment I'm testing this from my home computer over a VPN and the behavior is a little different from what I was seeing on my work computer (OS and R versions will be slightly different. I'll update this with the specific details from my work computer tomorrow.) Running

    library(DBI)
    library(odbc)
    dbConnect(odbc::odbc(),"OracleODBC-12c")

yields

    Error: nanodbc/nanodbc.cpp:950: IM002: [unixODBC][Driver Manager]Data source name not found, and no default driver specified 

On my work computer, the error was actually referencing the driver path and saying file not found, but that's not happening on my home computer. The database is Oracle 11.2.0.4.0. I can successfully connect via ROracle and RODBC (using Actual Tech drivers configured using the ODBC Manager GUI).

I downloaded the Instant Client ODBC files (for 12.0.4.0, I didn't see any for 11.*) and put them in the same directory that I have all the other Instant Client files that are used by ROracle, and where my tnsnames.ora file is.

Running `odbcinst -j` yields:

> unixODBC 2.3.2
> DRIVERS............: /usr/local/Cellar/unixodbc/2.3.2_1/etc/odbcinst.ini
> SYSTEM DATA SOURCES: /usr/local/Cellar/unixodbc/2.3.2_1/etc/odbc.ini
> FILE DATA SOURCES..: /usr/local/Cellar/unixodbc/2.3.2_1/etc/ODBCDataSources
> USER DATA SOURCES..: /Users/elias/.odbc.ini
> SQLULEN Size.......: 8
> SQLLEN Size........: 8
> SQLSETPOSIROW Size.: 8

I've tried using odbc.ini and odncinst.ini files in various locations (e.g. editing the ones listed above, creating version in ~/ODBC and setting ODBCSYSINI environment variable) with the odbcinst.ini containing

> [Oracle Driver]
> Description     = Oracle ODBC driver for Oracle 12c
> Driver          = path/to/libsqora.dylib.12.1
> Setup           =
> FileUsage       =
> CPTimeout       =
> CPReuse         =

and the odbc.ini file containing:

> [OracleODBC-12c]
> Application Attributes  = T
> Attributes              = W
> BatchAutocommitMode     = IfAllSuccessful
> BindAsFLOAT             = F
> CloseCursor             = F
> DisableDPM              = F
> DisableMTS              = T
> Driver                  = Oracle Driver
> DSN                     = OracleODBC-12c
> EXECSchemaOpt           =
> EXECSyntax              = T
> Failover                = T
> FailoverDelay           = 10
> FailoverRetryCount      = 10
> FetchBufferSize         = 64000
> ForceWCHAR              = F
> Lobs                    = T
> Longs                   = T
> MaxLargeData            = 0
> MetadataIdDefault       = F
> QueryTimeout            = T
> ResultSets              = T
> DataBase                = [=SID in tnsnames.ora]
> ServerName              = [=Host in tnsnames.ora]
> Port                    = [=Port in tnanames.ora]
> SQLGetData extensions   = F
> Translation DLL         =
> Translation Option      = 0
> DisableRULEHint         = T
> UserID                  = [my user id]
> Password                = [mypassword]
> StatementCache          = F
> CacheBufferSize         = 20
> UseOCIDescribeAny       = F
> SQLTranslateErrors      = F
> MaxTokenSize            = 8192
> AggregateSQLType        = FLOAT

I basically cribbed all that from the odbc_update_ini.sh file that came with the Instant Client ODBC download.

My `sessionInfo()` is:

> R version 3.3.3 (2017-03-06)
> Platform: x86_64-apple-darwin13.4.0 (64-bit)
> Running under: OS X El Capitan 10.11.6
> 
> locale:
> [1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8
> 
> attached base packages:
> [1] stats     graphics  grDevices utils     datasets  methods   base     
> 
> other attached packages:
> [1] odbc_1.1.1      DBI_0.7         devtools_1.13.2
> 
> loaded via a namespace (and not attached):
>  [1] bit_1.1-12    hms_0.3       tools_3.3.3   withr_1.0.2   tibble_1.3.0  yaml_2.1.14   Rcpp_0.12.11  memoise_1.0.0 bit64_0.9-5   blob_1.1.0    digest_0.6.12

I'll comment again with details from my work computer tomorrow, which is an OS version behind, but otherwise should be basically the same. Not sure why it would be different.

**Comment by joranE** [comment]
So a little more poking around and I can now get as far on my home computer as my work machine.

The difference was that I _have_ to create `.odbc.ini` and `.odcninst.ini` files in my `$HOME` directory, _not_ in a subdirectory. It has to be the top level, and then I have to set `ODBCSYSINI = $HOME`.

Otherwise it appears to ignore any other .ini files, no matter how I point to them.

With the .ini files set up like this, odbc seems to "see" everything:

> > odbcListDrivers()
>            name attribute value
> 1 SQLite Driver      <NA>  <NA>
> 2 Oracle Driver      <NA>  <NA>
> > odbcListDataSources()
>             name   description
> 1         SQLite SQLite Driver
> 2 OracleODBC-12c Oracle Driver

...and I can successfully create a SQLite connection (yay!) but trying to connect to the Oracle db yields:

> Error: nanodbc/nanodbc.cpp:950: 01000: [unixODBC][Driver Manager]Can't open lib 'path/to/libsqora.dylib.12.1' : file not found

so the error is referencing the actual file location now, just like on my machine at work. Phew!

**Comment by jimhester** [comment]
The file not found error is likely due to a missing shared library that `libsqora.dylib` is trying to load. On macOS you can use `otool -L` on the dylib file to see what shared libraries it is using, one or more should be missing. The linux equivalent is `ldd`.

The oracle driver requires the Oracle instant client library to be in your shared library path, set with `LD_LIBRARY_PATH`. See http://www.oracle.com/technetwork/database/features/oci/odbc-ic-releasenotes-094306.html for some more information on this.

**Comment by joranE** [comment]
Yeah, I'm aware of the DYLD_LIBRARY_PATH dance from all the ROracle installations I've done. `otool -L` returns:

libsqora.dylib.12.1:
	@rpath/libsqora.dylib.12.1 (compatibility version 0.0.0, current version 0.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1213.0.0)
	@rpath/libclntsh.dylib.12.1 (compatibility version 0.0.0, current version 0.0.0)
	@rpath/libodbcinst.2.dylib (compatibility version 3.0.0, current version 3.0.0)

from which maybe I should conclude that I need `libclntsh.dylib.12.1` (I've got `libclntsh.11.1` currently) in that directory?

**Comment by jimhester** [comment]
It looks like some of the output got cut off in your message so I can't say for sure, did you figure out the dependency issue?

**Comment by joranE** [comment]
I have made some progress, I think. At least, I think the problem now may be simply the specific format and values in the odbcinst.ini and odbc.ini files.

I upgraded to instantclient 12.1 (instantclient, sdk and odbc downloads), installed it all in `opt/ora12/instantclient_12_1` per the instructions for ROracle installation, recompiled ROracle against that and confirmed that all that worked fine.

Now I get the error:

> Error: nanodbc/nanodbc.cpp:950: HY000: [unixODBC][Oracle][ODBC][Ora]ORA-12541: TNS:no listener

I'm not sure what else to try at this point.

**Comment by jimhester** [comment]
You can try some of the solutions in the following https://stackoverflow.com/questions/13358656/oracle-client-ora-12541-tnsno-listener

**Comment by joranE** [comment]
Unfortunately, the suggestions there all assume that I have control over the db, which I don't. Feel free to close this if you want, if I ever figure this out I'll swing back and leave a comment. I don't want you to waste any more time just helping me.

**Comment by loudoro** [comment]
Hi! I'm getting the same error below and wondering if you've resolved the issue.

`Error: nanodbc/nanodbc.cpp:950: 01000: [unixODBC][Driver Manager]Can't open lib 'path/to/libsqora.dylib.12.1' : file not found`

otool -L results in the follow output but I'm not sure what to do next:

```
	@rpath/libsqora.dylib.12.1 (compatibility version 0.0.0, current version 0.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1213.0.0)
	@rpath/libclntsh.dylib.12.1 (compatibility version 0.0.0, current version 0.0.0)
	@rpath/libodbcinst.2.dylib (compatibility version 3.0.0, current version 3.0.0)
```

Many thanks!
