### ISSUE TITLE
dbWriteTable() throws Restricted data type attribute violation for Dates

### ISSUE THREAD

**Issue by luongjames8** [rstats-db/odbc#88]
### Issue Description and Expected Result
dbWriteTable() throws Restricted data type attribute violation for Dates

### Database
MS SQL Server (Azure)
12.00.0600

### Reproducible Example
I have a data table with the following definition that I'm trying to save to my SQL database using the dbWriteTable function in DBI via ODBC.

```
'data.frame':	102 obs. of  5 variables:
 $ Ticker  : chr  "CLU7 Comdty" "CLU7 Comdty" "CLU7 Comdty" "CLU7 Comdty" ...
 $ date    : Date, format: "2017-05-18" "2017-05-19" "2017-05-22" "2017-05-23" ...
 $ PX_LAST : num  50.1 51.1 51.6 51.9 51.8 ...
 $ VOLUME  : num  44674 49488 49892 61507 82223 ...
 $ OPEN_INT: int  188049 187709 186073 191824 192922 193801 197856 200787 205011 204793 ...
```

Example:
```
library(DBI)
library(odbc)

drv <- dbDriver("odbc")
con <- dbConnect(drv,"StyxDB", uid = "xxxxx", pwd = "xxxx")
dbWriteTable(con, "new20", flatFrame, verbose=TRUE)

```
Pretty standard stuff. Except that it throws this error because of the values in the Date column
```
Error in result_insert_dataframe(rs@ptr, values) : 
  nanodbc/nanodbc.cpp:1791: 07006: [Microsoft][ODBC Driver 13 for SQL Server]Restricted data type 
attribute violation 
```
Previously I had used RODBC::sqlSave and it had no issue writing the same data set back to the SQL server. 

I have tried saving this data frame as a CSV and importing it into say MS Excel or Access using the same date format with no text conversion issues.

If I convert the dates to characters, everything uploads smoothly.

I have some existing data which I used RODBC::sqlSave to upload. If I download that data set and reupload it, there seems to be no problem. However, there seems to be no noticable problems with the current set.

<details>
<summary>Session Info</summary>

```r
devtools::session_info()
Session info ------------------------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.4.0 (2017-04-21)
 system   x86_64, mingw32             
 ui       RStudio (1.0.143)           
 language (EN)                        
 collate  English_United States.1252  
 tz       Asia/Kuala_Lumpur           
 date     2017-07-11                  

Packages ----------------------------------------------------------------------------------------------------------------
 package    * version date       source        
 base       * 3.4.0   2017-04-21 local         
 bit          1.1-12  2014-04-09 CRAN (R 3.4.0)
 bit64        0.9-7   2017-05-08 CRAN (R 3.4.0)
 blob         1.1.0   2017-06-17 CRAN (R 3.4.1)
 compiler     3.4.0   2017-04-21 local         
 datasets   * 3.4.0   2017-04-21 local         
 DBI        * 0.7     2017-06-18 CRAN (R 3.4.1)
 devtools   * 1.13.2  2017-06-02 CRAN (R 3.4.1)
 digest       0.6.12  2017-01-27 CRAN (R 3.4.0)
 graphics   * 3.4.0   2017-04-21 local         
 grDevices  * 3.4.0   2017-04-21 local         
 hms          0.3     2016-11-22 CRAN (R 3.4.1)
 memoise      1.1.0   2017-04-21 CRAN (R 3.4.1)
 methods    * 3.4.0   2017-04-21 local         
 odbc       * 1.1.1   2017-06-27 CRAN (R 3.4.1)
 R6           2.2.2   2017-06-17 CRAN (R 3.4.1)
 Rcpp         0.12.11 2017-05-22 CRAN (R 3.4.0)
 rlang        0.1.1   2017-05-18 CRAN (R 3.4.1)
 RODBC        1.3-15  2017-04-13 CRAN (R 3.4.0)
 rstudioapi   0.6     2016-06-27 CRAN (R 3.4.1)
 stats      * 3.4.0   2017-04-21 local         
 tibble       1.3.3   2017-05-28 CRAN (R 3.4.1)
 tools        3.4.0   2017-04-21 local         
 utils      * 3.4.0   2017-04-21 local         
 withr        1.0.2   2016-06-20 CRAN (R 3.4.1)
```
</details>

**Comment by luongjames8** [comment]
OK in the spirit of trying to replicate this very confusing problem. I've done this. Here's the structure of one line of the data table that yields the restricted data type problem:

```
> str(oneLine)
'data.frame':	1 obs. of  4 variables:
 $ Ticker  : Factor w/ 1 level "CLU7 Comdty": 1
 $ date    : Date, format: "2017-05-18"
 $ VOLUME  : num 44674
 $ OPEN_INT: int 188049
```
Then I try to write this one line to the database in a new table and I get the attribute violation error.
```
 dbWriteTable(con, "new7", oneLine, verbose=TRUE, overwrite=TRUE)
Error in result_insert_dataframe(rs@ptr, values) : 
  nanodbc/nanodbc.cpp:1791: 07006: [Microsoft][ODBC Driver 13 for SQL Server]Restricted data type attribute violation 
```
So now I try to clone the data frame:
```
 rep_data <- data.frame(Ticker=as.factor("CLU7 Comdty"), date = as.Date("2017-05-18"), VOLUME=44674, OPEN_INT =as.integer(188049))
> str(rep_data)
'data.frame':	1 obs. of  4 variables:
 $ Ticker  : Factor w/ 1 level "CLU7 Comdty": 1
 $ date    : Date, format: "2017-05-18"
 $ VOLUME  : num 44674
 $ OPEN_INT: int 188049

```
Exactly the same.... 

`dbWriteTable(con, "new8", rep_data, verbose=TRUE, `overwrite=TRUE)`

But this write function produces no error.

**Comment by jimhester** [comment]
Try using `dput()` on the objects to verify they have exactly the same data, I can verify the last example works without error as well.

**Comment by ruiyiz** [comment]
The culprit is likely the internal date representation of Rblpapi. For some reason, the date values returned by Rblpapi are somehow different from vanilla R dates and cause trouble with database packages.

It doesn't cause problems in other packages (RODBC, RSQLServer) probably because these packages convert dates to string literals before interacting with the underlying database (can't remember which one does so).

As a workaround, you may convert the dates returned by Rblpapi to characters, and then convert to the proper R dates, before any 'odbc' operations.

Long-term solutions may be: 1) report the issue to Rblpapi; and/or 2) coerce dates to string literals in the sqlData method.

**Comment by luongjames8** [comment]
Thanks for the suggestions!

As suggested, I have used `dput()` on both datasets, which I've pasted below. 

```
> dput(oneLine)
structure(list(Ticker = structure(1L, .Label = "CLU7 Comdty", class = "factor"), 
    date = structure(17304L, class = "Date"), VOLUME = 44674, 
    OPEN_INT = 188049L), .Names = c("Ticker", "date", "VOLUME", 
"OPEN_INT"), row.names = 1L, class = "data.frame")

> dput(rep_data)
structure(list(Ticker = structure(1L, .Label = "CLU7 Comdty", class = "factor"), 
    date = structure(17304, class = "Date"), VOLUME = 44674, 
    OPEN_INT = 188049L), .Names = c("Ticker", "date", "VOLUME", 
"OPEN_INT"), row.names = c(NA, -1L), class = "data.frame")
```

The date does seem to be stored slightly differently, even though it displays the same. The faulting date in the oneLine object,   `date = structure(17304L, class = "Date")` seems to append an **L** at the end of the date. Not sure what the effect of that is.

Sorry I have just installed reprex but haven't tinkered with it enough for this example.
