### ISSUE TITLE
64 Bit integers

### ISSUE THREAD

**Issue by jimhester** [rstats-db/odbc#9]
### Issue Description and Expected Result
64 Bit integers are able to be read and written from databases. Currently they are converted to 32 bit native R integers (i.e. nonsense).

### Database
All databases that support 64 bit integers.

### Reproducible Example
``` r
library(DBI)
library(odbconnect)
con <- dbConnect(odbconnect::odbconnect(), dsn = "PostgreSQL")
dbGetQuery(con, "SELECT 10000000000 as a")
#>            a
#> 1 1410065408
```

### Session Info
<details>

``` r
devtools::session_info()
#> Session info -------------------------------------------------------------
#>  setting  value                       
#>  version  R version 3.3.0 (2016-05-03)
#>  system   x86_64, darwin13.4.0        
#>  ui       X11                         
#>  language (EN)                        
#>  collate  en_US.UTF-8                 
#>  tz       America/New_York            
#>  date     2016-11-07
#> Packages -----------------------------------------------------------------
#>  package    * version     date       source                            
#>  assertthat   0.1         2013-12-06 CRAN (R 3.3.0)                    
#>  blob         0.0.0.9000  2016-11-03 Github (jimhester/blob@d677541)   
#>  clipr        0.2.1       2016-06-23 CRAN (R 3.3.0)                    
#>  colorspace   1.2-7       2016-10-11 cran (@1.2-7)                     
#>  crayon       1.3.2       2016-06-28 cran (@1.3.2)                     
#>  DBI        * 0.5-12      2016-10-13 Github (rstats-db/DBI@4f00863)    
#>  DBItest      1.3-10      2016-11-03 local (jimhester/DBItest@8284aef) 
#>  devtools     1.12.0.9000 2016-10-28 Github (hadley/devtools@f0d1c7e)  
#>  digest       0.6.10      2016-08-02 CRAN (R 3.3.0)                    
#>  evaluate     0.10        2016-10-11 cran (@0.10)                      
#>  ggplot2    * 2.1.0.9001  2016-10-28 Github (hadley/ggplot2@cd6a691)   
#>  gtable       0.2.0       2016-02-26 CRAN (R 3.3.0)                    
#>  htmltools    0.3.5       2016-03-21 CRAN (R 3.3.0)                    
#>  knitr        1.14.15     2016-11-07 Github (yihui/knitr@8cbc61a)      
#>  lazyeval     0.2.0.9000  2016-06-15 Github (hadley/lazyeval@c155c3d)  
#>  magrittr     1.5         2014-11-22 cran (@1.5)                       
#>  memoise      1.0.0.9001  2016-10-28 local (jimhester/memoise@bd541fb) 
#>  munsell      0.4.3       2016-02-13 CRAN (R 3.3.0)                    
#>  nvimcom    * 0.9-23      2016-09-26 local                             
#>  odbconnect * 0.0.0.9000  <NA>       local                             
#>  plyr         1.8.4       2016-06-08 cran (@1.8.4)                     
#>  R6           2.2.0       2016-10-05 cran (@2.2.0)                     
#>  Rcpp         0.12.7      2016-09-05 CRAN (R 3.3.0)                    
#>  reprex       0.0.0.9001  2016-05-11 Github (jennybc/reprex@826ddf4)   
#>  rmarkdown    1.1.9010    2016-10-28 Github (rstudio/rmarkdown@6305a8e)
#>  roxygen2     5.0.1       2015-11-11 CRAN (R 3.3.0)                    
#>  rprojroot    1.0-2       2016-03-28 cran (@1.0-2)                     
#>  rstudioapi   0.6         2016-06-27 cran (@0.6)                       
#>  scales       0.4.0.9003  2016-10-13 Github (hadley/scales@d58d83a)    
#>  stringi      1.1.2       2016-10-01 CRAN (R 3.3.0)                    
#>  stringr      1.1.0.9000  2016-11-07 Github (hadley/stringr@e030642)   
#>  testthat   * 1.0.2.9000  2016-10-07 local (jimhester/testthat@11b3316)
#>  tibble       1.2-12      2016-10-13 Github (hadley/tibble@7c4a712)    
#>  withr        1.0.2       2016-06-20 Github (jimhester/withr@91279ae)
```
</details>

**Comment by bquinart** [comment]
We have many bigint values in our datasets and are encountering this 'bug' (with Netezza and Impala).
RODBC maps it to num. Would you do the same?
This is not something odbc specific, but integer values above 53 bits loose precision when converted to the R num type. I wonder if there are solutions for that.

**Comment by aschmu** [comment]
@bquinart  Hi, just curious are you using a DBI compliant ODBC driver for Impala ? I've been looking for one of these to no avail.

**Comment by bquinart** [comment]
Hi @aschmu. I am still getting started with R. I use package RODBCDBI (which wraps RODBC) on top of the Cloudera ODBC driver (which is Simba OEM).
This odbc packages looks like a good alternative (again using the Cloudera ODBC driver).
Cloudera also released https://github.com/cloudera/hs2client. Which is a C++ library that connects directly to Impala. That would be a good candidate for a specific R package. Unfortunately it still lacks functionality and looks like development has already stopped.

**Comment by jimhester** [comment]
Yes we are aware of the current limitations using R integers is done mainly on compliance with the DBItest package suite (as you observed with the test failures from your PR).

The plan is to provide full support for 64 bit integers in the future using one of the existing solutions such as [bit64](https://cran.r-project.org/package=bit64), or another similar package. However this will require additional changes to the DBItest package to accommodate it.

cc @krlmlr

**Comment by tsp** [comment]
What about adding an option to return BIGINTs as strings until proper support is added?

**Comment by jimhester** [comment]
You can use the [bit64](https://github.com/rstats-db/odbc/tree/bit64) branch, which we should be merging in the near future.

**Comment by jimhester** [comment]
We now support 64 bit integers, returning them as bit64 'integer64' objects.
