### ISSUE TITLE
Options for mapping BIGINT

### ISSUE THREAD

**Issue by khotilov** [rstats-db/odbc#90]
In Vertica, all integer types are synonyms for the same signed 64-bit BIGINT. With the change in #9 to use the bit64's integer64 type to represent such numbers, all my integer columns are now pulled as integer64. In general, I tend to use integer64 only when really necessary, and to stay away from using them for computations as much as possible b/c of hidden quirks such as
```R
> mean(1:2L)
[1] 1.5
> mean(as.integer64(1:2L))
integer64
[1] 1
```
That is, integer64 is not a drop-in replacement for integers.

Would it be possible to have a global configuration option for how BIGINT is mapped? E.g.:
- "integer64" (default)
- "integer" coerce to integer (user must be aware of possible consequences)
- "numeric" coerce to double

**Comment by cprosser** [comment]
I second this. Using the package with Hive/Hadoop is causing issues for me too because bit64 doesn’t work so well. In my case, loading a stored session (via .Rdata in RStudio) does the wrong thing until you force bit64 to load. This was causing difficulties with Rmd files where I was just trying to reevaluate a cell at the end of the workbook.

**Comment by khotilov** [comment]
I've attempted to add this functionality in https://github.com/rstats-db/odbc/compare/master...khotilov:bigint_map - it seems to work well. Please let me know if it's ok for a PR, or if any other approach would be more appropriate.

**Comment by jimhester** [comment]
I think if we were going to go this route of having this be user specified
it should be a parameter when creating the connection and included in the
connection object.

I am not convinced the option is a good idea however...

**Comment by khotilov** [comment]
@jimhester You are right, this should be included in the connection object. It cannot be a global option since there could be more than one connection. However, allowing to set the bigint mapping only when creating a connection is too restrictive, since one might need to change it for some specific queries, and I'd rather not open another connection for that. I've done some corresponding code changes in https://github.com/rstats-db/odbc/compare/master...khotilov:bigint_map

I'm not sure what are your remaining reservations, but I don't see any acceptable way to handle it in a non-user-specified manner when a database has only one integer type (64 bit), and most of times, but not always, I want to bring such data into R as 32 bit integers.

**Comment by aschmu** [comment]
Just curious, how does RODBC handle BIGINT ?

**Comment by khotilov** [comment]
@aschmu RODBC pulls BIGINT in as character, and then uses `utils::type.convert` which converts it either to integer or to numeric as appropriate. The problem with it is that it could be unstable when there are not many values out of 32 bit limits, leading to type mismatch issues in some situations. So I was explicitly converting such columns to numeric in my queries.

There is also a Vertica-tailored https://github.com/vertica/DistributedR/tree/master/vRODBC package, where they simply convert BIGINT columns (which in Vertica means all integer columns) to numeric. RJDBC does the same thing. BTW, I've included an option for "numeric" to be able to replicate such behavior.

**Comment by khotilov** [comment]
It would also be good to warn a user when they choose "integer" mapping, but some values are out of range...

**Comment by jimhester** [comment]
Ok, I extended your branch with some additional things and **odbc** now supports

- integer64
- integer
- numeric
- character

Mappings for 64 bit integers, set by `odbcSetBigIntMapping()`

**Comment by jimhester** [comment]
I agree that warning about out of range values would be nice, but it is unfortunately somewhat challenging to detect due to the way that columns are bound.

**Comment by khotilov** [comment]
@jimhester thank you. that looks great!

**Comment by hadley** [comment]
I think this should only be a connection level setting. Making it a global option adds much extra complexity for little extra gain.
